//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UIStackView, UITextField, _SFJavaScriptDialogTextView, _SFJavaScriptDialogView;

__attribute__((visibility("hidden")))
@interface _SFJavaScriptDialogContentView : UIView
{
    _SFJavaScriptDialogTextView *_messageTextView;
    UITextField *_promptTextField;
    NSArray *_layoutConstraintsWhenPromptIsVisible;
    UIView *_separatorView;
    UIStackView *_actionButtonsView;
    UIButton *_primaryActionButton;
    UIButton *_secondaryActionButton;
    _Bool _hasSecondaryAction;
    _SFJavaScriptDialogView *_dialogView;
}

@property(nonatomic) __weak _SFJavaScriptDialogView *dialogView; // @synthesize dialogView=_dialogView;
- (void).cxx_destruct;
- (void)_invokeDelegateWithPrimaryAction:(_Bool)arg1;
- (void)_invokeSecondaryAction;
- (void)_invokePrimaryAction;
- (void)setPrimaryActionTitle:(id)arg1 secondaryActionTitle:(id)arg2;
- (void)endEditingInPrompt;
- (void)setPromptText:(id)arg1;
- (void)setMessageText:(id)arg1;
- (void)_updatePropertiesDefinedByContentSizeCategory;
- (void)layoutSubviews;
- (void)updateConstraints;
- (id)keyCommands;
- (_Bool)canBecomeFirstResponder;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

