//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSLayoutConstraint, UILayoutGuide, UIStackView, _SFQuickLookDocumentInfoView;
@protocol _SFQuickLookDocumentViewDelegate;

@interface _SFQuickLookDocumentView : UIView
{
    UIView *_backgroundView;
    UIView *_contentView;
    _SFQuickLookDocumentInfoView *_documentInfoView;
    NSArray *_actionButtons;
    UIStackView *_actionButtonsView;
    NSLayoutConstraint *_topContentInsetConstraint;
    UILayoutGuide *_topLayoutGuide;
    NSLayoutConstraint *_topLayoutGuideHeightConstraint;
    id <_SFQuickLookDocumentViewDelegate> _delegate;
}

@property(nonatomic) __weak id <_SFQuickLookDocumentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_actionButtonTapped:(id)arg1;
- (void)_updatePropertiesDefinedByContentSizeCategory;
- (void)_setUpLayoutConstraints;
- (struct CGRect)frameForButtonAtIndex:(unsigned long long)arg1;
- (void)updateTopContentInset:(double)arg1;
- (void)updateDocumentIcon:(id)arg1;
- (void)updateDocumentFileType:(id)arg1;
- (void)updateDocumentFileSize:(id)arg1;
- (void)updateDocumentFileName:(id)arg1;
- (void)updateActionTitles:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

