//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (SafariServicesExtras)
- (double)_sf_convertY:(double)arg1 toCoordinateSpace:(id)arg2;
@property(readonly, nonatomic) _Bool _sf_hasLandscapeAspectRatio;
@property(readonly, nonatomic) _Bool _sf_usesLeftToRightLayout;
@property(readonly, nonatomic) _Bool _sf_isFullScreenSized;
@end

