//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;
@protocol OS_dispatch_queue;

@interface _CDQueryRankerConfiguration : NSObject
{
    NSUserDefaults *defaults;
    NSObject<OS_dispatch_queue> *queue;
}

- (void).cxx_destruct;
@property(readonly) long long minimumPrefixLengthToSuggest;
@property(readonly) _Bool suggestPrefixWithoutEngagement;
@property(readonly) _Bool featureDisabled;
@property(readonly) _Bool suggestExpandedPrefix;
@property(readonly) _Bool suggestPrefixWhenNoMatchFound;
@property(readonly) _Bool suggestPrefixOnPunchout;
@property(readonly) _Bool suggestPrefixAlways;
@property(readonly) unsigned long long model;
@property long long modelVersionNumber;
- (void)registerHandlerForFeatureDisabledNotification:(CDUnknownBlockType)arg1;
- (void)registerHandlerForDeleteDataNotification:(CDUnknownBlockType)arg1;
- (void)registerHandlerForModelChangeNotification:(CDUnknownBlockType)arg1;
- (id)initWithDefaults:(id)arg1;
- (id)init;

@end

