//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSSet, NSString;

@interface _DKSourceMO : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) NSString *bundleId; // @dynamic bundleId;
@property(retain, nonatomic) NSString *deviceId; // @dynamic deviceId;
@property(retain, nonatomic) NSSet *object; // @dynamic object;
@property(nonatomic) long long sourceHash; // @dynamic sourceHash;
@property(nonatomic) short userId; // @dynamic userId;
@end

