//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SGQPStoredMessage : NSObject
{
    _Bool _isSent;
    NSString *_content;
    struct SGUnixTimestamp_ _creationTimestamp;
}

+ (id)messageWithContent:(id)arg1 isSent:(_Bool)arg2 creationTimestamp:(struct SGUnixTimestamp_)arg3;
+ (id)sortByCreationDesc:(id)arg1;
+ (id)messageWithContent:(id)arg1 isSent:(_Bool)arg2;
@property(readonly, nonatomic) struct SGUnixTimestamp_ creationTimestamp; // @synthesize creationTimestamp=_creationTimestamp;
@property(readonly, nonatomic) _Bool isSent; // @synthesize isSent=_isSent;
@property(readonly, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)description;
- (id)initWithContent:(id)arg1 isSent:(_Bool)arg2 creationTimestamp:(struct SGUnixTimestamp_)arg3;
- (id)init;

@end

