//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface SGTextMessageConversationTracker : NSObject
{
    struct _opaque_pthread_mutex_t _lock;
    NSMutableArray *_conversationIdsMRU;
    NSMutableDictionary *_conversations;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)clear;
- (id)addMessage:(id)arg1;
- (id)init;

@end

