//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface SKUIPendingRentalCenter : NSObject
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    NSMutableDictionary *_mutableRentals;
    _Bool _userLoggedIn;
    _Bool _fetching;
}

+ (id)_sharedDateFormatter;
@property _Bool fetching; // @synthesize fetching=_fetching;
- (void).cxx_destruct;
- (void)_processFetchedDownloads:(id)arg1;
- (void)_mediaLibraryDidChangeNotification:(id)arg1;
- (void)_loadPendingRentals;
- (void)_accountStoreDidChangeNotification:(id)arg1;
- (id)rentalInformationForMediaItem:(id)arg1;
- (void)dealloc;
- (id)init;

@end

