//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreCDP/NSSecureCoding-Protocol.h>

@class NSString;

@interface CDPFollowUpContext : NSObject <NSSecureCoding>
{
    _Bool _shouldNotify;
    NSString *_followUpType;
}

+ (_Bool)supportsSecureCoding;
+ (id)contextForOfflinePasscodeChange;
+ (id)contextForStateRepair;
+ (id)contextWithType:(id)arg1;
@property(copy, nonatomic) NSString *followUpType; // @synthesize followUpType=_followUpType;
@property(nonatomic) _Bool shouldNotify; // @synthesize shouldNotify=_shouldNotify;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

