//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Widgets/WGWidgetListViewControllerDelegate-Protocol.h>

@class UIView, WGWidgetListViewController;
@protocol UIViewControllerTransitionCoordinator;

@protocol WGWidgetListViewControllerDelegatePrivate <WGWidgetListViewControllerDelegate>
- (long long)widgetListViewController:(WGWidgetListViewController *)arg1 columnModeForTransitionToSize:(struct CGSize)arg2 withCoordinator:(id <UIViewControllerTransitionCoordinator>)arg3;
- (long long)activeColumnModeForWidgetListViewController:(WGWidgetListViewController *)arg1;
- (UIView *)widgetListViewController:(WGWidgetListViewController *)arg1 newCustomBackgroundViewForItemInList:(id)arg2;
@end

