//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PDFDocument;

@interface PDFViewLayoutPrivate : NSObject
{
    id delegate;
    _Bool delegateKnowsMargins;
    _Bool delegateKnowsScaleFactor;
    _Bool delegateKnowsDisplayMode;
    _Bool delegateKnowsDisplayAsBook;
    _Bool delegateKnowsDisplayBox;
    _Bool delegateKnowsDisplaySoloPagesCentered;
    _Bool delegateKnowsDisplayRTL;
    _Bool delegateKnowsDisableInterpageSpacing;
    _Bool delegateKnowsFlipped;
    struct CGSize singlePageContinuousSize;
    struct CGSize twoUpContinousSize;
    struct CGRect *pageLayoutBounds;
    PDFDocument *document;
    unsigned long long pageCount;
    struct _NSRange pageSubrange;
}

- (void).cxx_destruct;

@end

