//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TSgPTPTime : NSObject
{
    unsigned int _nanoseconds;
    unsigned long long _seconds;
}

@property(nonatomic) unsigned int nanoseconds; // @synthesize nanoseconds=_nanoseconds;
@property(nonatomic) unsigned long long seconds; // @synthesize seconds=_seconds;
@property(nonatomic) unsigned long long nanoseconds64Representation; // @dynamic nanoseconds64Representation;

@end

