//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Accounts/ACAccount.h>

@class NSArray, NSString;

@interface ACAccount (VSAAdditions)
@property(readonly, copy, nonatomic) NSArray *channelIDs;
@property(readonly, copy, nonatomic) NSArray *postalCodes;
@property(readonly, copy, nonatomic) NSString *householdID;
@property(readonly, copy, nonatomic) NSString *identityProviderID;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *identityProviderDisplayName;
@end

