//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <VideoSubscriberAccount/VSAViewModel.h>

@class NSString;
@protocol VSAAutoAuthenticationViewModelDelegate;

__attribute__((visibility("hidden")))
@interface VSAAutoAuthenticationViewModel : VSAViewModel
{
    id <VSAAutoAuthenticationViewModelDelegate> _delegate;
    NSString *_headerTitle;
    NSString *_headerSubtitle;
    NSString *_message;
    NSString *_footerTitle;
    NSString *_footerButtonText;
}

@property(copy, nonatomic) NSString *footerButtonText; // @synthesize footerButtonText=_footerButtonText;
@property(copy, nonatomic) NSString *footerTitle; // @synthesize footerTitle=_footerTitle;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *headerSubtitle; // @synthesize headerSubtitle=_headerSubtitle;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(nonatomic) __weak id <VSAAutoAuthenticationViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didSelectFooterButton;
- (id)init;

@end

