//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, VSAKeychainEditingContext;

@interface VSAAccountStore : NSObject
{
    VSAKeychainEditingContext *_keychainEditingContext;
    id _changeObserver;
}

@property(nonatomic) __weak id changeObserver; // @synthesize changeObserver=_changeObserver;
@property(retain, nonatomic) VSAKeychainEditingContext *keychainEditingContext; // @synthesize keychainEditingContext=_keychainEditingContext;
- (void).cxx_destruct;
- (void)removeAccount:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)saveAccount:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
@property(readonly, copy, nonatomic) NSArray *accounts;
- (id)firstAccount;
- (id)_keychainItemsWithLimit:(unsigned long long)arg1;
- (id)_accountForKeychainItem:(id)arg1;
- (void)_underlyingDataDidChange;
- (void)dealloc;
- (id)init;

@end

