//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, VSAAccountStore, VSAKeychainGenericPassword;

@interface VSAAccount : NSObject
{
    VSAAccountStore *_accountStore;
    NSString *_accountTypeDescription;
    NSString *_accountDescription;
    NSString *_identityProviderDisplayName;
    NSString *_identityProviderID;
    NSString *_username;
    NSString *_authenticationToken;
}

@property(copy, nonatomic) NSString *authenticationToken; // @synthesize authenticationToken=_authenticationToken;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *identityProviderID; // @synthesize identityProviderID=_identityProviderID;
@property(copy, nonatomic) NSString *identityProviderDisplayName; // @synthesize identityProviderDisplayName=_identityProviderDisplayName;
@property(copy, nonatomic) NSString *accountDescription; // @synthesize accountDescription=_accountDescription;
@property(copy, nonatomic) NSString *accountTypeDescription; // @synthesize accountTypeDescription=_accountTypeDescription;
@property(nonatomic) __weak VSAAccountStore *accountStore; // @synthesize accountStore=_accountStore;
- (void).cxx_destruct;
- (id)description;
@property(retain, nonatomic) VSAKeychainGenericPassword *keychainItem;

@end

