//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class VSAPrivacyFacade;

@interface VSABundlePrivacyInfo : NSObject
{
    struct __CFBundle *_bundle;
    VSAPrivacyFacade *_privacyFacade;
}

@property(readonly, nonatomic) VSAPrivacyFacade *privacyFacade; // @synthesize privacyFacade=_privacyFacade;
@property(readonly, nonatomic) struct __CFBundle *bundle; // @synthesize bundle=_bundle;
- (void).cxx_destruct;
@property(nonatomic, getter=isAccessGranted) _Bool accessGranted;
- (void)dealloc;
- (id)initWithBundle:(struct __CFBundle *)arg1 privacyFacade:(id)arg2;

@end

