//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <VideoSubscriberAccount/VSAViewModel.h>

@class NSArray, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface VSACredentialEntryViewModel : VSAViewModel
{
    _Bool _showFooter;
    _Bool _needsUpdateValidationButtonState;
    NSArray *_fields;
    NSString *_message;
    NSString *_footerText;
    NSURL *_linkURL;
    NSString *_linkTitle;
    NSArray *_originalFieldTextValues;
}

@property(retain, nonatomic) NSArray *originalFieldTextValues; // @synthesize originalFieldTextValues=_originalFieldTextValues;
@property(nonatomic) _Bool needsUpdateValidationButtonState; // @synthesize needsUpdateValidationButtonState=_needsUpdateValidationButtonState;
@property(copy, nonatomic) NSString *linkTitle; // @synthesize linkTitle=_linkTitle;
@property(copy, nonatomic) NSURL *linkURL; // @synthesize linkURL=_linkURL;
@property(copy, nonatomic) NSString *footerText; // @synthesize footerText=_footerText;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) _Bool showFooter; // @synthesize showFooter=_showFooter;
@property(copy, nonatomic) NSArray *fields; // @synthesize fields=_fields;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_setNeedsUpdateValidationButtonState;
- (void)_updateValidationButtonState;
- (void)dealloc;

@end

