//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <VideoSubscriberAccount/VSAStoreRequestOperation.h>

@class NSArray;

@interface VSAIdentityProviderFetchAllOperation : VSAStoreRequestOperation
{
    NSArray *_supportedAccountProviderIDs;
    NSArray *_featuredIdentityProviders;
}

@property(copy, nonatomic) NSArray *featuredIdentityProviders; // @synthesize featuredIdentityProviders=_featuredIdentityProviders;
@property(copy, nonatomic) NSArray *supportedAccountProviderIDs; // @synthesize supportedAccountProviderIDs=_supportedAccountProviderIDs;
- (void).cxx_destruct;
- (void)handleResponseObject:(id)arg1;
- (id)URLBagKey;
- (id)init;

@end

