//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface VSAServiceProviderAppMapping : NSObject
{
    NSString *_serviceProviderID;
    NSString *_appAdamID;
}

@property(readonly, copy, nonatomic) NSString *appAdamID; // @synthesize appAdamID=_appAdamID;
@property(readonly, copy, nonatomic) NSString *serviceProviderID; // @synthesize serviceProviderID=_serviceProviderID;
- (void).cxx_destruct;
- (id)initWithServiceProviderID:(id)arg1 appAdamID:(id)arg2;
- (id)init;

@end

