//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <VideoSubscriberAccount/VSAAsyncOperation.h>

@class NSDictionary, NSError, NSString, SSRequest;

@interface VSAStoreRequestOperation : VSAAsyncOperation
{
    int _requestCompletionFlag;
    NSError *_error;
    SSRequest *_request;
}

@property(retain, nonatomic) SSRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)cancel;
- (void)executionDidBegin;
- (void)_handleResponseData:(id)arg1;
- (_Bool)_isFirstToFinish;
- (void)handleResponseObject:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *requestParameters;
@property(readonly, copy, nonatomic) NSString *URLBagKey;

@end

