//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <VideoSubscriberAccount/NSCopying-Protocol.h>
#import <VideoSubscriberAccount/NSSecureCoding-Protocol.h>

@class VSAccountMetadata, VSResourceAuthorization;

@interface VSAViewServiceResponse : NSObject <NSCopying, NSSecureCoding>
{
    VSResourceAuthorization *_authorization;
    VSAccountMetadata *_accountMetadata;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) VSAccountMetadata *accountMetadata; // @synthesize accountMetadata=_accountMetadata;
@property(copy, nonatomic) VSResourceAuthorization *authorization; // @synthesize authorization=_authorization;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

