//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <VideoSubscriberAccount/VSAViewServiceRemoteViewControllerDelegate-Protocol.h>

@class NSString, VSAViewServiceRemoteViewController, VSAViewServiceRequest, VSResourceAuthorizationRequest;
@protocol VSAViewServiceHostViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface VSAViewServiceHostViewController : UIViewController <VSAViewServiceRemoteViewControllerDelegate>
{
    _Bool _addedRemoteViewController;
    VSAViewServiceRequest *_viewServiceRequest;
    id <VSAViewServiceHostViewControllerDelegate> _delegate;
    VSResourceAuthorizationRequest *_authorizationRequest;
    VSAViewServiceRemoteViewController *_remoteViewController;
}

@property(nonatomic) _Bool addedRemoteViewController; // @synthesize addedRemoteViewController=_addedRemoteViewController;
@property(retain, nonatomic) VSAViewServiceRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;
@property(copy, nonatomic) VSResourceAuthorizationRequest *authorizationRequest; // @synthesize authorizationRequest=_authorizationRequest;
@property(nonatomic) __weak id <VSAViewServiceHostViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy, nonatomic) VSAViewServiceRequest *viewServiceRequest; // @synthesize viewServiceRequest=_viewServiceRequest;
- (void).cxx_destruct;
- (void)_didInstantiateRemoteViewController;
- (void)_addRemoteViewControllerAsChildViewController;
- (void)_connectToViewService;
- (void)viewServiceRemoteViewControllerDidCancel:(id)arg1;
- (void)viewServiceRemoteViewControllerDidChooseAdditionalProviders:(id)arg1;
- (void)viewServiceRemoteViewController:(id)arg1 didFailWithError:(id)arg2;
- (void)viewServiceRemoteViewController:(id)arg1 didFinishWithResponse:(id)arg2;
- (void)dismissViewServiceRemoteViewController:(id)arg1;
- (void)presentViewServiceRemoteViewController:(id)arg1;
- (long long)modalPresentationStyle;
- (void)_cancelButtonPressed:(id)arg1;
- (void)_failWithError:(id)arg1;
- (id)initWithViewServiceRequest:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

