//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthKit/_HKBaseAchievementPredicateEnvironment.h>

@class NSString, _HKAchievementPredicateActivityDataEnvironment, _HKAchievementPredicateDatesEnvironment, _HKAchievementPredicateWorkoutsEnvironment;

@interface _HKAchievementPredicateEnvironment : _HKBaseAchievementPredicateEnvironment
{
    NSString *_currentCountryCode;
    _HKAchievementPredicateActivityDataEnvironment *_activityData;
    _HKAchievementPredicateDatesEnvironment *_dates;
    _HKAchievementPredicateWorkoutsEnvironment *_workouts;
}

@property(readonly, nonatomic) _HKAchievementPredicateWorkoutsEnvironment *workouts; // @synthesize workouts=_workouts;
@property(readonly, nonatomic) _HKAchievementPredicateDatesEnvironment *dates; // @synthesize dates=_dates;
@property(readonly, nonatomic) _HKAchievementPredicateActivityDataEnvironment *activityData; // @synthesize activityData=_activityData;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *currentCountryCode;
- (void)setCurrentLocale:(id)arg1;
- (id)initWithActivityDataEnvironment:(id)arg1 datesEnvironment:(id)arg2 workoutsEnvironment:(id)arg3;

@end

