//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GLKit/GLKView.h>

@class CADisplayLink, UIScreen;

@interface HKGLView : GLKView
{
    UIScreen *_screen;
    CADisplayLink *_displayLink;
    _Bool _displayLinkPaused;
    _Bool _viewIsVisible;
    _Bool _viewWillMoveToWindow;
    double _lastUpdateTime;
    _Bool _needsRender;
    unsigned int _latestDrawErrror;
    _Bool _synchronizesWithCA;
    _Bool _alwaysRequiresDisplayLink;
    float _preferredFramesPerSecond;
}

+ (void)_clearCachedProgramForVertexShader:(id)arg1 fragmentShader:(id)arg2;
@property(nonatomic) _Bool alwaysRequiresDisplayLink; // @synthesize alwaysRequiresDisplayLink=_alwaysRequiresDisplayLink;
@property(nonatomic) float preferredFramesPerSecond; // @synthesize preferredFramesPerSecond=_preferredFramesPerSecond;
@property(nonatomic) _Bool synchronizesWithCA; // @synthesize synchronizesWithCA=_synchronizesWithCA;
- (void).cxx_destruct;
- (void)_updateGLLayerIsAsynchronous;
- (void)_loadVertexShaderSource:(id)arg1 fragmentShaderSource:(id)arg2 forProgram:(unsigned int *)arg3;
- (void)_loadVertexShader:(id)arg1 fragmentShader:(id)arg2 inBundle:(id)arg3 forProgram:(unsigned int *)arg4 cache:(_Bool)arg5;
- (void)setNeedsRender;
- (id)snapshot;
- (void)drawRect:(struct CGRect)arg1;
- (unsigned int)drawInRect:(struct CGRect)arg1;
- (void)update;
- (_Bool)viewIsVisible;
@property(readonly, nonatomic) double timeSinceLastUpdate;
@property(nonatomic, getter=isPaused) _Bool paused;
- (void)layoutSubviews;
- (void)willMoveToWindow:(id)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)didMoveToWindow;
- (void)_updateScreenIfChanged;
- (void)_resumeByNotification;
- (void)_pauseByNotification;
- (void)_update;
- (void)_displayLinkFired;
- (void)_createDisplayLinkForScreen:(id)arg1;
- (_Bool)_isLastUpdateTimeValid;
- (void)_invalidateLastUpdateTime;
- (_Bool)_needsDisplayLink;
- (void)dealloc;
- (void)_commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

