//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/_HDAchievementState.h>

@class NSDate;

@interface _HDExerciseAchievementState : _HDAchievementState
{
    _Bool _briskMinutesGoalJustMetToday;
    double _bestBriskMinutes;
    double _previousBestBriskMinutes;
    double _briskMinutesToday;
    double _briskMinutesYesterday;
    long long _consecutiveGoalsMet;
    long long _lastResetSummaryIndexForStreaks;
    NSDate *_lastPerfectWeekDate;
}

@property(retain, nonatomic) NSDate *lastPerfectWeekDate; // @synthesize lastPerfectWeekDate=_lastPerfectWeekDate;
@property(nonatomic) long long lastResetSummaryIndexForStreaks; // @synthesize lastResetSummaryIndexForStreaks=_lastResetSummaryIndexForStreaks;
@property(nonatomic) long long consecutiveGoalsMet; // @synthesize consecutiveGoalsMet=_consecutiveGoalsMet;
@property(nonatomic) _Bool briskMinutesGoalJustMetToday; // @synthesize briskMinutesGoalJustMetToday=_briskMinutesGoalJustMetToday;
@property(nonatomic) double briskMinutesYesterday; // @synthesize briskMinutesYesterday=_briskMinutesYesterday;
@property(nonatomic) double briskMinutesToday; // @synthesize briskMinutesToday=_briskMinutesToday;
@property(nonatomic) double previousBestBriskMinutes; // @synthesize previousBestBriskMinutes=_previousBestBriskMinutes;
@property(nonatomic) double bestBriskMinutes; // @synthesize bestBriskMinutes=_bestBriskMinutes;
- (void).cxx_destruct;

@end

