//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HDAchievementDataStore, HDAchievementDefinitions, NSCalendar, NSDate;
@protocol HDAchievementEngineDelegate, HDDailyGoalDetectionDelegate;

@interface HDAchievementEngine : NSObject
{
    id <HDDailyGoalDetectionDelegate> _dailyGoalDetectionDelegate;
    NSCalendar *_cachedCalendar;
    id <HDAchievementEngineDelegate> _delegate;
    HDAchievementDataStore *_dataStore;
    HDAchievementDefinitions *_achievementDefinitions;
    NSDate *_fixedNowDate;
    NSCalendar *_fixedCalendar;
}

+ (_Bool)_isCompleteWithNumberOfWeeks:(unsigned long long)arg1 dateToday:(id)arg2 consecutiveCompleteDays:(unsigned long long)arg3 inCalendar:(id)arg4;
+ (long long)_differenceInDaysBetweenActivitySummaryIndex:(long long)arg1 andIndex:(long long)arg2 inCalendar:(id)arg3 dayLimit:(unsigned long long)arg4;
@property(retain, nonatomic) NSCalendar *fixedCalendar; // @synthesize fixedCalendar=_fixedCalendar;
@property(retain, nonatomic) NSDate *fixedNowDate; // @synthesize fixedNowDate=_fixedNowDate;
@property(readonly, nonatomic) HDAchievementDefinitions *achievementDefinitions; // @synthesize achievementDefinitions=_achievementDefinitions;
@property(nonatomic) __weak HDAchievementDataStore *dataStore; // @synthesize dataStore=_dataStore;
@property(nonatomic) __weak id <HDAchievementEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_sanityCheckDate:(id)arg1 now:(id)arg2 defaultDate:(id)arg3;
- (id)_calendar;
- (id)_now;
- (void)systemTimeZoneDidChange;
- (id)_generateAchievementWithDefinition:(id)arg1 environment:(id)arg2;
- (void)runForTriggers:(unsigned long long)arg1 withEnvironment:(id)arg2;
- (unsigned long long)runForNewCombinedActivityData;
- (unsigned long long)runForNewMoveData;
- (void)runForStepAchievements;
- (unsigned long long)runForNewStandData;
- (unsigned long long)runForNewExerciseData;
- (unsigned long long)runForNewWorkouts;
- (id)initWithAchievementDefinitions:(id)arg1 dailyGoalDetectionDelegate:(id)arg2;
- (id)init;

@end

