//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSIndexSet, NSLocale;

@interface HDAchievementDefinitions : NSObject
{
    NSIndexSet *_stepCountMilestones;
    NSIndexSet *_lifetimeCompleteDayMilestones;
    NSArray *_supportedWorkoutActivityTypes;
    NSLocale *_locale;
}

@property(retain, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
@property(retain, nonatomic) NSArray *supportedWorkoutActivityTypes; // @synthesize supportedWorkoutActivityTypes=_supportedWorkoutActivityTypes;
@property(retain, nonatomic) NSIndexSet *lifetimeCompleteDayMilestones; // @synthesize lifetimeCompleteDayMilestones=_lifetimeCompleteDayMilestones;
@property(retain, nonatomic) NSIndexSet *stepCountMilestones; // @synthesize stepCountMilestones=_stepCountMilestones;
- (void).cxx_destruct;
- (id)_locale;
- (unsigned long long)minimumDaysOfHistoryForBestBriskMinutesAchievement;
- (unsigned long long)minimumDaysOfHistoryForBestDailyCaloriesAchievement;
- (_Bool)canHaveMultipleAchievementsForStepCount:(unsigned long long)arg1;
- (double)minimumDurationFor7WorkoutsInWeekAchievement;
- (double)minimumDurationForFirstWorkoutOfTypeAchievement;
- (unsigned long long)totalWorkoutCountRequiredForBestWorkoutAchievements;

@end

