//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/NSObject-Protocol.h>

@class HDFitnessFriendsActivityDataManager, NSArray;

@protocol HDFitnessFriendsActivityDataManagerDelegate <NSObject>

@optional
- (void)fitnessFriendsActivityDataManager:(HDFitnessFriendsActivityDataManager *)arg1 recievedNewSnapshots:(NSArray *)arg2 workouts:(NSArray *)arg3 achievements:(NSArray *)arg4;
@end

