//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NCNotificationAction, NSString, UILabel, UIView;

@interface NCNotificationListCellActionButton : UIControl
{
    _Bool _backgroundBlurred;
    NCNotificationAction *_notificationAction;
    NSString *_title;
    UILabel *_titleLabel;
    UIView *_backgroundView;
    UIView *_backgroundOverlayView;
}

@property(retain, nonatomic) UIView *backgroundOverlayView; // @synthesize backgroundOverlayView=_backgroundOverlayView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic, getter=isBackgroundBlurred) _Bool backgroundBlurred; // @synthesize backgroundBlurred=_backgroundBlurred;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NCNotificationAction *notificationAction; // @synthesize notificationAction=_notificationAction;
- (void).cxx_destruct;
- (void)_unHighlightButton:(id)arg1;
- (void)_highlightButton:(id)arg1;
- (long long)_wordCountForText:(id)arg1;
- (unsigned long long)_numberOfLinesInLabel:(id)arg1;
- (double)_singleLineHeightForMeasurement;
- (struct CGSize)_sizeOfLabel:(id)arg1 thatFitsSize:(struct CGSize)arg2;
- (double)_titleBaselineOffset;
- (void)_layoutTitleLabel;
- (void)_layoutBackgroundOverlayView;
- (void)_layoutBackgroundView;
- (void)_configureBackgroundOverlayViewIfNecessary;
- (void)_configureBackgroundViewIfNecessary;
- (void)_configureTitleLabelIfNecessary;
- (void)setHighlighted:(_Bool)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

