//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (NCAdditions)
+ (id)nc_animatedImageWithImageSource:(struct CGImageSource *)arg1;
+ (id)nc_animatedImageWithFileURL:(id)arg1;
@end

