//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Messages/NSObject-Protocol.h>

@class MSMessage, NSArray, NSString, NSURL, NSUUID, UIImage;

@protocol MSMessageContext <NSObject>
@property(readonly, nonatomic) MSMessage *inputMessagePayload;
@property(readonly, nonatomic) NSArray *recipientIdentifiers;
@property(readonly, nonatomic) NSUUID *senderIdentifier;
@property(readonly, nonatomic) NSString *conversationIdentifier;
- (void)insertStickerWithMediaAtURL:(NSURL *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)insertStickerWithImage:(UIImage *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)insertMediaAtURL:(NSURL *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)insertMediaAtURL:(NSURL *)arg1 attributionURL:(NSURL *)arg2 attributionIcon:(UIImage *)arg3 completionHandler:(void (^)(NSError *))arg4;
- (void)insertImage:(UIImage *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)insertText:(NSString *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)updateMessagePayload:(MSMessage *)arg1 completionHandler:(void (^)(NSError *))arg2;
@end

