//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <Messages/UICollectionViewDataSource-Protocol.h>
#import <Messages/UICollectionViewDelegate-Protocol.h>

@class MSStickerBrowserViewLayoutSpec, NSMutableArray, NSString, NSTimer, UICollectionView, UICollectionViewFlowLayout;
@protocol MSStickerBrowserViewDataSource, MSStickerBrowserViewDisplayDelegate;

@interface MSStickerBrowserView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    long long _stickerSize;
    id <MSStickerBrowserViewDataSource> _dataSource;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_flowLayout;
    MSStickerBrowserViewLayoutSpec *_layoutSpec;
    NSMutableArray *_cellsToAnimate;
    NSTimer *_animationTimer;
    unsigned long long _currentlyAnimatingIndex;
    id <MSStickerBrowserViewDisplayDelegate> _displayDelegate;
}

@property(nonatomic) id <MSStickerBrowserViewDisplayDelegate> displayDelegate; // @synthesize displayDelegate=_displayDelegate;
@property(nonatomic) unsigned long long currentlyAnimatingIndex; // @synthesize currentlyAnimatingIndex=_currentlyAnimatingIndex;
@property(retain, nonatomic) NSTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
@property(retain, nonatomic) NSMutableArray *cellsToAnimate; // @synthesize cellsToAnimate=_cellsToAnimate;
@property(retain, nonatomic) MSStickerBrowserViewLayoutSpec *layoutSpec; // @synthesize layoutSpec=_layoutSpec;
@property(retain, nonatomic) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <MSStickerBrowserViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) long long stickerSize; // @synthesize stickerSize=_stickerSize;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long stickerSizeClass;
- (void)_updateCollectionViewSpecIfNeeded;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)layoutSubviews;
- (id)_stickerAtIndexPath:(id)arg1;
- (void)reloadData;
- (void)animateNextCell;
- (void)configureStickerView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 layout:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 stickerSizeClass:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 stickerSize:(long long)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

