//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNFuture;

@interface CNAutocompleteInputStringTokenizer : NSObject
{
    CNFuture *_nameStringTokenizer;
}

+ (id)lazyNameStringTokenizerWithLocale:(id)arg1;
+ (id)tokensFromString:(id)arg1;
@property(retain) CNFuture *nameStringTokenizer; // @synthesize nameStringTokenizer=_nameStringTokenizer;
- (void).cxx_destruct;
- (CDUnknownBlockType)expandCJKNames;
- (id)tokensFromString:(id)arg1;
- (id)initWithLocale:(id)arg1;
- (id)init;

@end

