//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SceneKit/SCNRenderer.h>

@interface SCNOffscreenRenderer : SCNRenderer
{
}

+ (id)offscreenRendererWithContext:(id)arg1 size:(struct CGSize)arg2;
@property(nonatomic) unsigned long long antialiasingMode;
@property(nonatomic) struct CGSize size;
@property(readonly, nonatomic) unsigned int textureID;
- (id)snapshot;

@end

