//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuickLook/QLDetailItemViewController.h>

@class QLDetailItemViewControllerState, QLRoundProgressView, UIImage, UIImageView, _QLDownloadOperation;
@protocol QLDownloadingItemViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface QLDownloadingItemViewController : QLDetailItemViewController
{
    _Bool _downloading;
    _Bool _downloaded;
    _Bool _didDisappear;
    id _progressSubscriber;
    QLRoundProgressView *_progressView;
    QLDetailItemViewControllerState *_readyForDownloadState;
    QLDetailItemViewControllerState *_cancelableDownloadingState;
    QLDetailItemViewControllerState *_nonCancelableDownloadingState;
    QLDetailItemViewControllerState *_completedDownloadState;
    _QLDownloadOperation *_downloadOperation;
    UIImageView *_downloadImageView;
    UIImage *_cloudImage;
    id <QLDownloadingItemViewControllerDelegate> _downloadingDelegate;
}

@property _Bool downloaded; // @synthesize downloaded=_downloaded;
@property __weak id <QLDownloadingItemViewControllerDelegate> downloadingDelegate; // @synthesize downloadingDelegate=_downloadingDelegate;
@property(retain) QLRoundProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (id)_newDownloadOperation;
- (void)_presentConnectivityAlert;
- (void)_setDownloading:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_stopDownload:(_Bool)arg1;
- (void)_startDownload:(_Bool)arg1;
- (void)_toggleDownload:(_Bool)arg1;
- (void)performAction;
- (void)previewDidDisappear:(_Bool)arg1;
- (void)previewDidAppear:(_Bool)arg1;
- (void)_updateFileSizeWithProgress:(double)arg1 animated:(_Bool)arg2;
- (void)loadPreviewControllerWithPreviewItem:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setAppearance:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidLoad;

@end

