//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuickLook/QLTransitionDriver.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface QLZoomTransitionDriver : QLTransitionDriver
{
    UIView *_uncroppedView;
}

+ (void)cropView:(id)arg1 toAvoidNavigationOffset:(double)arg2 animationDuration:(double)arg3;
- (void).cxx_destruct;
- (void)tearDown;
- (void)_performZoomTransition;
- (void)animateFinishTransition;
- (void)animateTransition;

@end

