//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HKHealthStore, NSHashTable;
@protocol OS_dispatch_queue;

@interface FIUIWheelchairUseController : NSObject
{
    HKHealthStore *_healthStore;
    NSHashTable *_observers;
    long long _state;
    long long _wheelchairUse;
    NSObject<OS_dispatch_queue> *_queue;
    int _characteristicUpdateToken;
}

- (void).cxx_destruct;
- (void)_handleFetchSuccess:(id)arg1;
- (void)_handleFetchError:(id)arg1;
- (void)_fetchWheelchairUseIfNecessary;
- (_Bool)_needsFetch;
- (_Bool)isWheelchairUser;
- (void)_alertObserversDidUpdate;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)initWithHealthStore:(id)arg1;

@end

