//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIUIBackgroundMapImageGenerator : NSObject
{
}

+ (id)relativeColorForSpeed:(double)arg1 bottomSpeed:(double)arg2 topSpeed:(double)arg3 averageSpeed:(double)arg4;
+ (void)_overlayPinView:(id)arg1 point:(CDStruct_c3b9c2ee)arg2 onSnapshot:(id)arg3 context:(struct CGContext *)arg4 color:(id)arg5;
+ (id)_overlayPolyline:(id)arg1 pinView:(id)arg2 onSnapshot:(id)arg3 withLocationReadings:(id)arg4;
+ (void)mapImageWithSize:(struct CGSize)arg1 locationReadings:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

