//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeKitDaemon/HMDLogEvent.h>

#import <HomeKitDaemon/HMDAWDLogEvent-Protocol.h>

@class NSString;

@interface HMDAWDResultLogEvent : HMDLogEvent <HMDAWDLogEvent>
{
    unsigned int _resultType;
    unsigned int _transportType;
    unsigned int _isClient;
}

+ (id)logEventAWDResultWithResultType:(unsigned int)arg1 transportType:(unsigned int)arg2 isClient:(unsigned int)arg3;
+ (id)uuid;
+ (void)initialize;
@property(nonatomic) unsigned int isClient; // @synthesize isClient=_isClient;
@property(nonatomic) unsigned int transportType; // @synthesize transportType=_transportType;
@property(nonatomic) unsigned int resultType; // @synthesize resultType=_resultType;
- (id)metricForAWD;
- (unsigned int)AWDMessageType;
- (id)initWithResultType:(unsigned int)arg1 transportType:(unsigned int)arg2 isClient:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

