//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeKitDaemon/HMDVideoStreamLastDecodedFrameDelegate-Protocol.h>
#import <HomeKitDaemon/HMFLogging-Protocol.h>
#import <HomeKitDaemon/HMFTimerDelegate-Protocol.h>

@class HMDCameraLastDecodedFrameWaitTimer, NSMutableSet, NSString;
@protocol HMDCameraStreamSnapshotHandlerDelegate, OS_dispatch_queue;

@interface HMDCameraStreamSnapshotHandler : NSObject <HMFLogging, HMFTimerDelegate, HMDVideoStreamLastDecodedFrameDelegate>
{
    NSMutableSet *_videoStreamInterfaces;
    NSMutableSet *_lastDecodedFrameTimers;
    id <HMDCameraStreamSnapshotHandlerDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSObject<OS_dispatch_queue> *_workQueue;
    HMDCameraLastDecodedFrameWaitTimer *_lastFrameWaitTimer;
}

+ (id)logCategory;
@property(retain, nonatomic) HMDCameraLastDecodedFrameWaitTimer *lastFrameWaitTimer; // @synthesize lastFrameWaitTimer=_lastFrameWaitTimer;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
@property(readonly, nonatomic) id <HMDCameraStreamSnapshotHandlerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSMutableSet *lastDecodedFrameTimers; // @synthesize lastDecodedFrameTimers=_lastDecodedFrameTimers;
@property(readonly, nonatomic) NSMutableSet *videoStreamInterfaces; // @synthesize videoStreamInterfaces=_videoStreamInterfaces;
- (void).cxx_destruct;
- (void)_callDidGetNewSnapshot:(id)arg1;
- (void)videoStream:(id)arg1 didGetLastDecodedFrame:(id)arg2;
- (void)timerDidFire:(id)arg1;
- (void)captureLastFrame:(id)arg1;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

