//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeKitDaemon/HMDCameraStreamControlManager.h>

#import <HomeKitDaemon/HMDCameraIDSDeviceConnectionSenderDelegate-Protocol.h>
#import <HomeKitDaemon/HMDCameraIDSSessionInitiatorDelegate-Protocol.h>
#import <HomeKitDaemon/HMDCameraStreamControlManagerProtocol-Protocol.h>
#import <HomeKitDaemon/HMDStreamingManagerDelegate-Protocol.h>

@class HMDCameraMediaConfigGenerator, HMDCameraSupportedConfigurationCache, HMDLocalStreamSession, NSString;

@interface HMDCameraLocalStreamControlManager : HMDCameraStreamControlManager <HMDStreamingManagerDelegate, HMDCameraIDSSessionInitiatorDelegate, HMDCameraIDSDeviceConnectionSenderDelegate, HMDCameraStreamControlManagerProtocol>
{
    HMDLocalStreamSession *_streamSession;
    HMDCameraMediaConfigGenerator *_configGenerator;
    HMDCameraSupportedConfigurationCache *_supportedConfigCache;
}

+ (id)logCategory;
@property(retain, nonatomic) HMDCameraSupportedConfigurationCache *supportedConfigCache; // @synthesize supportedConfigCache=_supportedConfigCache;
@property(retain, nonatomic) HMDCameraMediaConfigGenerator *configGenerator; // @synthesize configGenerator=_configGenerator;
@property(retain, nonatomic) HMDLocalStreamSession *streamSession; // @synthesize streamSession=_streamSession;
- (void).cxx_destruct;
- (void)_sendUpdatedConfiguration;
- (void)_reconfigureStreams;
- (void)streamingManagerDidUpdateConfiguration:(id)arg1;
- (void)streamingManagerDidNetworkDeteriorate:(id)arg1;
- (void)streamingManagerDidNetworkImprove:(id)arg1;
- (void)streamingManagerDidStopStream:(id)arg1;
- (void)streamingManager:(id)arg1 didStartRelay:(id)arg2;
- (void)streamingManager:(id)arg1 didStartStream:(id)arg2 slotIdentifier:(id)arg3;
- (void)deviceConnectionSender:(id)arg1 didEndSession:(id)arg2;
- (void)deviceConnectionSender:(id)arg1 didSetup:(id)arg2;
- (void)sessionInitiator:(id)arg1 didEndSession:(id)arg2;
- (void)sessionInitiator:(id)arg1 didSetup:(id)arg2;
- (void)_streamStarted;
- (void)_cleanUpStreamSession;
- (void)_writeStopConfig;
- (void)_writeSelectConfig:(id)arg1 reconfigure:(_Bool)arg2;
- (void)_writeReselectConfig;
- (void)_writeStartConfig;
- (void)_stopCurrentStreamSession;
- (void)stopStream;
- (void)_reconfigureStream:(id)arg1;
- (void)reconfigureStream:(id)arg1;
- (void)_startStreamingManager;
- (void)_startStream:(id)arg1;
- (void)startStream:(id)arg1;
- (void)_handleSetupEndPointRead:(id)arg1;
- (void)_sendSetupEndPointRead;
- (void)_writeSetupEndPoint;
- (void)_handleSupportedParameters:(id)arg1;
- (void)_getSupportedConfigurations;
- (void)_negotiateStream;
- (void)negotiateStream;
- (void)setAudioSetting:(unsigned long long)arg1;
- (void)remoteSetup;
- (void)dealloc;
- (id)initWithSessionID:(id)arg1 streamSnapshotHandler:(id)arg2 reachabilityPath:(unsigned long long)arg3 destinationID:(id)arg4 delegate:(id)arg5 delegateQueue:(id)arg6 accessory:(id)arg7 streamManagementService:(id)arg8 remoteCapabilities:(id)arg9 supportedConfigCache:(id)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

