//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeKitDaemon/HMDMerging-Protocol.h>
#import <HomeKitDaemon/HMFLogging-Protocol.h>
#import <HomeKitDaemon/NSSecureCoding-Protocol.h>

@class HMDAccount, HMFProductInfo, NSNumber, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface HMDDevice : NSObject <HMFLogging, HMDMerging, NSSecureCoding>
{
    _Bool _residentCapable;
    _Bool _remoteGatewayCapable;
    NSString *_name;
    HMFProductInfo *_productInfo;
    NSNumber *_version;
    NSUUID *_identifier;
    HMDAccount *_account;
    NSObject<OS_dispatch_queue> *_propertyQueue;
    NSString *_destination;
    NSUUID *_accountIdentifier;
}

+ (_Bool)supportsSecureCoding;
+ (id)logCategory;
+ (id)shortDescription;
+ (_Bool)isRemoteGatewayCapableDevice:(id)arg1;
+ (_Bool)isResidentCapableDevice:(id)arg1;
+ (id)versionForDevice:(id)arg1;
+ (id)accountIdentifierFromDevice:(id)arg1 error:(id *)arg2;
+ (id)accountIdentifierFromDeviceUniqueIdentifier:(id)arg1 error:(id *)arg2;
+ (id)identifierFromDeviceDestination:(id)arg1 error:(id *)arg2;
+ (id)destinationForDevice:(id)arg1;
+ (id)deviceDestinationForDevice:(id)arg1;
+ (_Bool)isValidDestination:(id)arg1;
+ (id)identifierFromDevice:(id)arg1 error:(id *)arg2;
+ (id)namespace;
+ (id)deviceWithDestination:(id)arg1;
+ (id)currentDeviceWithIDSAccount:(id)arg1;
+ (id)deviceDestinationForDestination:(id)arg1;
+ (void)initialize;
@property(readonly, copy, nonatomic) NSUUID *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
@property(readonly, copy, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *propertyQueue; // @synthesize propertyQueue=_propertyQueue;
@property(nonatomic) __weak HMDAccount *account; // @synthesize account=_account;
@property(readonly, copy, nonatomic) NSUUID *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)mergeObject:(id)arg1;
- (id)logIdentifier;
@property(nonatomic, getter=isRemoteGatewayCapable) _Bool remoteGatewayCapable; // @synthesize remoteGatewayCapable=_remoteGatewayCapable;
@property(nonatomic, getter=isResidentCapable) _Bool residentCapable; // @synthesize residentCapable=_residentCapable;
@property(readonly, nonatomic, getter=isCurrentDevice) _Bool currentDevice;
@property(retain, nonatomic) NSNumber *version; // @synthesize version=_version;
@property(retain, nonatomic) HMFProductInfo *productInfo; // @synthesize productInfo=_productInfo;
- (void)setName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;
- (id)descriptionWithPointer:(_Bool)arg1;
- (id)shortDescription;
- (id)initWithIdentifier:(id)arg1 accountIdentifier:(id)arg2 name:(id)arg3 productInfo:(id)arg4 destination:(id)arg5 version:(id)arg6 isResidentCapable:(_Bool)arg7 isRemoteGatewayCapable:(_Bool)arg8;
- (id)initWithIDSDevice:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly) Class superclass;

@end

