//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeKitDaemon/HMFLogging-Protocol.h>
#import <HomeKitDaemon/HMFMessageReceiver-Protocol.h>

@class HMDAccountRegistry, HMDCentralMessageDispatcher, HMDHomeManager, HMDResidentMeshStorage, HMFMessageDispatcher, NSMutableArray, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface HMDResidentMesh : NSObject <HMFMessageReceiver, HMFLogging>
{
    _Bool _disableMesh;
    HMDHomeManager *_homeManager;
    NSUUID *_uuid;
    unsigned long long _broadcastRate;
    NSMutableArray *_internalMesh;
    HMDResidentMeshStorage *_ourStorage;
    NSObject<OS_dispatch_queue> *_workQueue;
    HMDAccountRegistry *_accountRegistry;
    HMFMessageDispatcher *_messageDispatcher;
    HMDCentralMessageDispatcher *_remoteMessageDispatcher;
}

+ (id)logCategory;
@property(nonatomic) _Bool disableMesh; // @synthesize disableMesh=_disableMesh;
@property(nonatomic) __weak HMDCentralMessageDispatcher *remoteMessageDispatcher; // @synthesize remoteMessageDispatcher=_remoteMessageDispatcher;
@property(nonatomic) __weak HMFMessageDispatcher *messageDispatcher; // @synthesize messageDispatcher=_messageDispatcher;
@property(nonatomic) __weak HMDAccountRegistry *accountRegistry; // @synthesize accountRegistry=_accountRegistry;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic) __weak HMDResidentMeshStorage *ourStorage; // @synthesize ourStorage=_ourStorage;
@property(retain, nonatomic) NSMutableArray *internalMesh; // @synthesize internalMesh=_internalMesh;
@property unsigned long long broadcastRate; // @synthesize broadcastRate=_broadcastRate;
@property(retain, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(readonly, nonatomic) __weak HMDHomeManager *homeManager; // @synthesize homeManager=_homeManager;
- (void).cxx_destruct;
- (id)logIdentifier;
- (void)dumpDebug;
- (id)dumpState;
- (id)deviceForAccessory:(id)arg1;
- (void)_updateMesh:(id)arg1;
- (void)_updateDevice:(id)arg1;
- (void)_updateDeviceResponse:(id)arg1 error:(id)arg2;
- (void)_handleMeshUpdateMessage:(id)arg1;
- (void)_handleMeshUpdateRequestMessage:(id)arg1;
- (void)_queueBroadcastForDevice:(id)arg1 forceBroadcast:(_Bool)arg2;
- (void)_updateMeshResponse:(id)arg1 error:(id)arg2;
- (void)_sendMessage:(id)arg1 payload:(id)arg2 target:(id)arg3 responseHandler:(CDUnknownBlockType)arg4;
- (id)_buildMessageForDevice:(id)arg1;
- (void)setEnabled:(_Bool)arg1 forDevice:(id)arg2;
- (_Bool)_setEnabled:(_Bool)arg1 forDevice:(id)arg2;
- (void)addDevice:(id)arg1;
- (void)_addDevice:(id)arg1;
- (void)removeDevice:(id)arg1;
- (void)_removeDevice:(id)arg1;
- (void)_removeConnectivityFromDeviceToAccessory:(id)arg1;
- (void)_addConnectivityFromDeviceToAccessory:(id)arg1;
- (void)setPreferredDevice:(id)arg1;
- (void)_setPreferredDevice:(id)arg1;
- (void)dealloc;
- (id)initWithHomeManager:(id)arg1 residentEnabled:(_Bool)arg2;
- (void)_deviceResidentChanged:(id)arg1;
- (void)_rdmRemoveResident:(id)arg1;
- (void)_rdmUpdateResident:(id)arg1;
- (void)_rdmAddResident:(id)arg1;
- (void)_accessoryIsNotReachable:(id)arg1;
- (void)_accessoryIsReachable:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *messageReceiveQueue;
@property(readonly, nonatomic) NSUUID *messageTargetUUID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

