//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HomeKitDaemon/HMFMessageReceiver-Protocol.h>

@class HMAccessoryCategory, HMDHome, HMFMessageDispatcher, NSMutableArray, NSString, NSUUID;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface HMDUnpairedAccessory : NSObject <HMFMessageReceiver>
{
    NSString *_identifier;
    NSString *_name;
    NSUUID *_uuid;
    HMFMessageDispatcher *_msgDispatcher;
    NSObject<OS_dispatch_queue> *_workQueue;
    NSMutableArray *_servers;
    HMAccessoryCategory *_category;
    NSObject<OS_dispatch_source> *_pairingRetryTimer;
    HMDHome *_home;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) __weak HMDHome *home; // @synthesize home=_home;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *pairingRetryTimer; // @synthesize pairingRetryTimer=_pairingRetryTimer;
@property(retain, nonatomic) HMAccessoryCategory *category; // @synthesize category=_category;
@property(retain, nonatomic) NSMutableArray *servers; // @synthesize servers=_servers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) HMFMessageDispatcher *msgDispatcher; // @synthesize msgDispatcher=_msgDispatcher;
@property(retain, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(copy, nonatomic, getter=getName) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *messageReceiveQueue;
@property(readonly, nonatomic) NSUUID *messageTargetUUID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)descriptionForTransportTypes;
@property(readonly, nonatomic) unsigned long long transportTypes;
- (void)_updateName:(id)arg1;
- (void)updateName:(id)arg1;
- (void)_updateCategory:(id)arg1 notifyClients:(_Bool)arg2;
- (void)updateCategory:(id)arg1;
- (void)_handleIdentify:(id)arg1;
- (void)_registerForMessages;
- (id)dumpDescription;
- (id)descriptionNonBlocking;
@property(readonly, copy) NSString *description;
- (_Bool)hasBTLELink;
- (id)accessoryServer;
- (id)accessoryServers;
- (_Bool)removeAccessoryServer:(id)arg1;
- (void)addAccessoryServer:(id)arg1;
- (id)initWithMessageDispatcher:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

