//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TXRPixelFormatInfo : NSObject
{
}

+ (unsigned char)componentsPerPixel:(unsigned long long)arg1;
+ (struct TXRImageMemoryLayout)packedMemoryLayoutForFormat:(unsigned long long)arg1 dimensions: /* Error: Ran out of types for this method. */;
+ (_Bool)hasAlpha:(unsigned long long)arg1;
+ (_Bool)isCompressed:(unsigned long long)arg1;
+ (_Bool)isInteger:(unsigned long long)arg1;
+ (unsigned char)pixelBytes:(unsigned long long)arg1;

@end

