//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface UNSecurityScopedURL : NSURL
{
    CDUnknownBlockType _sandboxExtensionIssuingBlock;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) CDUnknownBlockType sandboxExtensionIssuingBlock; // @synthesize sandboxExtensionIssuingBlock=_sandboxExtensionIssuingBlock;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)_allowsDirectEncoding;

@end

