//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ClockKit/CLKTextProvider.h>

@class NSDate, NSDateFormatter, NSTimeZone;

@interface CLKTimeTextProvider : CLKTextProvider
{
    NSDateFormatter *_dateFormatter;
    _Bool _preferToDropMinutesOrDesignator;
    _Bool _shouldDropMinutesIfWholeHour;
    NSDate *_date;
    NSTimeZone *_timeZone;
}

+ (_Bool)supportsSecureCoding;
+ (id)textProviderWithDate:(id)arg1 timeZone:(id)arg2;
+ (id)textProviderWithDate:(id)arg1;
@property(nonatomic) _Bool shouldDropMinutesIfWholeHour; // @synthesize shouldDropMinutesIfWholeHour=_shouldDropMinutesIfWholeHour;
@property(nonatomic) _Bool preferToDropMinutesOrDesignator; // @synthesize preferToDropMinutesOrDesignator=_preferToDropMinutesOrDesignator;
@property(retain, nonatomic) NSTimeZone *timeZone; // @synthesize timeZone=_timeZone;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
- (void).cxx_destruct;
- (id)JSONObjectRepresentation;
- (id)_initWithJSONObjectRepresentation:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)_validate;
- (id)_timeAttributedTextWithStyle:(id)arg1 dropMinutes:(_Bool)arg2 dropDesignator:(_Bool)arg3;
- (id)_sessionAttributedTextForIndex:(unsigned long long)arg1 withStyle:(id)arg2;

@end

