//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileReactorProxy.h>

@class NSFileProviderXPCMessenger, NSString;
@protocol NSFileProviderXPCInterface><NSXPCProxyCreating;

__attribute__((visibility("hidden")))
@interface NSFileProviderProxy : NSFileReactorProxy
{
    NSString *_secureID;
    id <NSFileProviderXPCInterface><NSXPCProxyCreating> _remoteProvider;
    NSFileProviderXPCMessenger *_forwardedMessenger;
    _Bool _wantsWriteNotifications;
}

@property _Bool wantsWriteNotifications; // @synthesize wantsWriteNotifications=_wantsWriteNotifications;
@property(readonly) id <NSFileProviderXPCInterface><NSXPCProxyCreating> remoteProvider; // @synthesize remoteProvider=_remoteProvider;
@property(readonly) NSString *secureID; // @synthesize secureID=_secureID;
- (void)observeEndOfWriteAtLocation:(id)arg1 forAccessClaim:(id)arg2;
- (void)observePresentationChangeOfKind:(id)arg1 withPresenter:(id)arg2 url:(id)arg3 newURL:(id)arg4;
- (void)provideLogicalURLForURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)providePhysicalURLForURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (CDUnknownBlockType)provideItemAtURL:(id)arg1 withOptions:(unsigned long long)arg2 forAccessClaim:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)invalidate;
- (void)forwardUsingProxy:(id)arg1;
- (void)setItemLocation:(id)arg1;
- (id)_clientProxy;
- (void)dealloc;
- (id)initWithClient:(id)arg1 remoteProvider:(id)arg2 reactorID:(id)arg3 secureID:(id)arg4;

@end

