//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UISettings.h>

@class CCUIControlCenterSettingsSectionSettings, CCUIControlCenterShortcutSectionSettings, UIColor;

@interface CCUIControlCenterSettings : _UISettings
{
    _Bool _highlightUsesPlusL;
    _Bool _forceVibrantControls;
    _Bool _useNewBounce;
    double _backgroundDarkening;
    double _platterWallpaperAlpha;
    CCUIControlCenterSettingsSectionSettings *_settingsSectionSettings;
    CCUIControlCenterShortcutSectionSettings *_shortcutSectionSettings;
    double _controlAlpha;
    double _controlAlpha1x;
    double _minControlAlpha;
    double _maxControlAlpha;
    double _disabledAlpha;
    double _disabledAlpha1x;
    double _highlightAlpha;
    double _glowAlpha;
    UIColor *_highlightColor;
    double _oldBounceFriction;
    double _bounceDensityFactor;
    double _bounceResistance;
    double _minVelocity;
    double _maxVelocity;
    double _attachmentThreshold;
    double _attachmentFrequencyAbove;
    double _attachmentFrequencyBelow;
    double _attachmentVelocityDamping;
    double _attachmentMinDamping;
    double _attachmentMaxDamping;
}

+ (id)settingsControllerModule;
@property double attachmentMaxDamping; // @synthesize attachmentMaxDamping=_attachmentMaxDamping;
@property double attachmentMinDamping; // @synthesize attachmentMinDamping=_attachmentMinDamping;
@property double attachmentVelocityDamping; // @synthesize attachmentVelocityDamping=_attachmentVelocityDamping;
@property double attachmentFrequencyBelow; // @synthesize attachmentFrequencyBelow=_attachmentFrequencyBelow;
@property double attachmentFrequencyAbove; // @synthesize attachmentFrequencyAbove=_attachmentFrequencyAbove;
@property double attachmentThreshold; // @synthesize attachmentThreshold=_attachmentThreshold;
@property double maxVelocity; // @synthesize maxVelocity=_maxVelocity;
@property double minVelocity; // @synthesize minVelocity=_minVelocity;
@property double bounceResistance; // @synthesize bounceResistance=_bounceResistance;
@property double bounceDensityFactor; // @synthesize bounceDensityFactor=_bounceDensityFactor;
@property double oldBounceFriction; // @synthesize oldBounceFriction=_oldBounceFriction;
@property _Bool useNewBounce; // @synthesize useNewBounce=_useNewBounce;
@property(retain) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property double glowAlpha; // @synthesize glowAlpha=_glowAlpha;
@property _Bool forceVibrantControls; // @synthesize forceVibrantControls=_forceVibrantControls;
@property _Bool highlightUsesPlusL; // @synthesize highlightUsesPlusL=_highlightUsesPlusL;
@property double highlightAlpha; // @synthesize highlightAlpha=_highlightAlpha;
@property double disabledAlpha1x; // @synthesize disabledAlpha1x=_disabledAlpha1x;
@property double disabledAlpha; // @synthesize disabledAlpha=_disabledAlpha;
@property double maxControlAlpha; // @synthesize maxControlAlpha=_maxControlAlpha;
@property double minControlAlpha; // @synthesize minControlAlpha=_minControlAlpha;
@property double controlAlpha1x; // @synthesize controlAlpha1x=_controlAlpha1x;
@property double controlAlpha; // @synthesize controlAlpha=_controlAlpha;
@property(retain) CCUIControlCenterShortcutSectionSettings *shortcutSectionSettings; // @synthesize shortcutSectionSettings=_shortcutSectionSettings;
@property(retain) CCUIControlCenterSettingsSectionSettings *settingsSectionSettings; // @synthesize settingsSectionSettings=_settingsSectionSettings;
@property double platterWallpaperAlpha; // @synthesize platterWallpaperAlpha=_platterWallpaperAlpha;
@property double backgroundDarkening; // @synthesize backgroundDarkening=_backgroundDarkening;
- (void).cxx_destruct;
- (double)resolvedDisabledAlpha;
- (double)resolvedControlAlpha;
- (void)setDefaultValues;

@end

