//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ContactsUICore/CNUIUserActionDiscovering-Protocol.h>

@class NSDictionary, NSLock, NSString;
@protocol CNUIUserActionDiscoveringEnvironment;

@interface CNUIUserActionDiscovering : NSObject <CNUIUserActionDiscovering>
{
    id <CNUIUserActionDiscoveringEnvironment> _discoveringEnvironment;
    NSDictionary *_targets;
    NSLock *_targetsLock;
}

@property(retain, nonatomic) NSLock *targetsLock; // @synthesize targetsLock=_targetsLock;
@property(retain, nonatomic) NSDictionary *targets; // @synthesize targets=_targets;
@property(readonly, nonatomic) id <CNUIUserActionDiscoveringEnvironment> discoveringEnvironment; // @synthesize discoveringEnvironment=_discoveringEnvironment;
- (void).cxx_destruct;
- (id)applicationProxiesForIntent:(id)arg1;
- (_Bool)isSkypeAvailable;
- (id)intentForActionType:(id)arg1;
- (id)thirdPartyTargetsForBundleIdentifier:(id)arg1;
- (id)thirdPartyTargetsForActionTypes:(id)arg1;
- (id)lazyTargetsForText;
- (id)lazyTargetsForVideo;
- (id)lazyTargetsForVoice;
- (id)lazyTargetsForEmail;
- (id)targetsForActionType:(id)arg1;
- (void)resetTargetsForActionType:(id)arg1;
- (id)observableForTargetsChangedForActionType:(id)arg1 schedulerProvider:(id)arg2;
- (id)initWithDiscoveringEnvironment:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

