//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VideosPlaybackSettings : NSObject
{
    int _videosPreferencesNotifyToken;
    _Bool _videosPreferenecsNotifyTokenIsValid;
    _Bool _cellularDataEnabled;
    unsigned long long _networkStatus;
    unsigned long long _playbackQuality;
}

+ (id)sharedSettings;
@property(nonatomic) unsigned long long playbackQuality; // @synthesize playbackQuality=_playbackQuality;
@property(nonatomic) unsigned long long networkStatus; // @synthesize networkStatus=_networkStatus;
@property(nonatomic, getter=isCellularDataEnabled) _Bool cellularDataEnabled; // @synthesize cellularDataEnabled=_cellularDataEnabled;
- (unsigned long long)_qualityForString:(id)arg1;
- (void)_populateNetworkValue;
- (void)_populateSettings;
- (void)_networkReachabilityChanged:(id)arg1;
- (void)_registerObserverForSettingsChange;
- (unsigned long long)networkStatusForNetworkType:(long long)arg1;
- (_Bool)networkHasConditionsForPlayback:(unsigned long long)arg1;
- (_Bool)hasNetworkConditionsForPlayback;
- (_Bool)hasANetworkConnection;
- (void)dealloc;
- (id)init;

@end

