//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface UIButton (HKAdditions)
+ (id)hk_medicalIDTintedRoundRectButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)hk_medicalIDTintedButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
@end

