//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <HomeUI/HMCameraStreamControlDelegate-Protocol.h>
#import <HomeUI/HUPresentationDelegate-Protocol.h>

@class HFCameraItem, HMCameraView, NSArray, NSString, UIActivityIndicatorView, UIButton, UISlider, UIView, UIVisualEffectView;
@protocol HUCameraStreamViewControllerDelegate;

@interface HUCameraStreamViewController : UIViewController <HUPresentationDelegate, HMCameraStreamControlDelegate>
{
    _Bool _microphoneEnabled;
    HMCameraView *_cameraView;
    HFCameraItem *_camera;
    id <HUCameraStreamViewControllerDelegate> _delegate;
    NSArray *_streamViewConstraints;
    UIActivityIndicatorView *_activityIndicator;
    UIView *_footerView;
    UIVisualEffectView *_footerBlurView;
    UISlider *_speakerVolumeSlider;
    UIButton *_microphoneButton;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(nonatomic) _Bool microphoneEnabled; // @synthesize microphoneEnabled=_microphoneEnabled;
@property(retain, nonatomic) UIButton *microphoneButton; // @synthesize microphoneButton=_microphoneButton;
@property(retain, nonatomic) UISlider *speakerVolumeSlider; // @synthesize speakerVolumeSlider=_speakerVolumeSlider;
@property(retain, nonatomic) UIVisualEffectView *footerBlurView; // @synthesize footerBlurView=_footerBlurView;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) NSArray *streamViewConstraints; // @synthesize streamViewConstraints=_streamViewConstraints;
@property(nonatomic) __weak id <HUCameraStreamViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) HFCameraItem *camera; // @synthesize camera=_camera;
@property(retain, nonatomic) HMCameraView *cameraView; // @synthesize cameraView=_cameraView;
- (void).cxx_destruct;
- (id)_cameraTitleString;
- (void)_addSubviews;
- (void)_createSubviews;
- (void)_updateMicrophoneButtonImage;
- (void)_stopCameraStream;
- (void)_startCameraStream;
- (void)updateViewConstraints;
- (void)cameraStreamControl:(id)arg1 didStopStreamWithError:(id)arg2;
- (void)cameraStreamControlDidStartStream:(id)arg1;
- (void)finishPresentation:(id)arg1 animated:(_Bool)arg2;
- (void)microphoneButtonPressed:(id)arg1;
- (void)speakerVolumeSliderValueChanged:(id)arg1;
- (void)_cameraDetailButtonPressed:(id)arg1;
- (void)_dismissCameraStreamButtonPressed:(id)arg1;
- (void)handleApplicationEnteredForeground:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCameraItem:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

