//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface HUCheckmarkCell : UITableViewCell
{
    _Bool _checked;
}

+ (id)_emptyCheckmarkPlaceholderImage;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

