//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeUI/NSObject-Protocol.h>

@protocol HUColorWheelSpace <NSObject>
@property(readonly, nonatomic) unsigned long long type;
- (CDStruct_02f6d515)coordinateForColor:(CDStruct_dbd0f16f)arg1 isValid:(out _Bool *)arg2;
- (CDStruct_dbd0f16f)colorForCoordinate:(CDStruct_02f6d515)arg1;

@optional
@property(nonatomic) unsigned long long mirroringBiasAxis;
@end

