//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeUI/HUGridCellLayoutOptions.h>

@interface HUGridCameraCellLayoutOptions : HUGridCellLayoutOptions
{
    double _headerViewHeight;
    double _cameraViewHeight;
    double _headerHorizontalInnerMargins;
}

+ (id)defaultOptionsForCellSizeSubclass:(long long)arg1;
@property(nonatomic) double headerHorizontalInnerMargins; // @synthesize headerHorizontalInnerMargins=_headerHorizontalInnerMargins;
@property(nonatomic) double cameraViewHeight; // @synthesize cameraViewHeight=_cameraViewHeight;
@property(nonatomic) double headerViewHeight; // @synthesize headerViewHeight=_headerViewHeight;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

