//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BLTDebugMetricsInterval;

@interface BLTDebugMetricsOnInterval : NSObject
{
    BLTDebugMetricsInterval *_interval;
}

@property(readonly, nonatomic) BLTDebugMetricsInterval *interval; // @synthesize interval=_interval;
- (void).cxx_destruct;
- (id)initWithInterval:(id)arg1;
- (id)init;

@end

