//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BBQuietModeOverrideAssertion, BBSettingsGateway, BLTRemoteObject, NPSManager, NSString;

@interface BLTDNDSyncInternal : NSObject
{
    NSString *_assertionOnBehalfOfActiveKey;
    NSString *_assertionActiveKey;
    unsigned long long _bulletinBoardDNDState;
    _Bool _isDNDMirrorEnabled;
    BBSettingsGateway *_settingsGateway;
    BLTRemoteObject *_connection;
    NPSManager *_npsManager;
    BBQuietModeOverrideAssertion *_dndAssertionOnBehalfOf;
}

@property(retain, nonatomic) BBQuietModeOverrideAssertion *dndAssertionOnBehalfOf; // @synthesize dndAssertionOnBehalfOf=_dndAssertionOnBehalfOf;
@property(readonly, nonatomic) unsigned long long bulletinBoardDNDState; // @synthesize bulletinBoardDNDState=_bulletinBoardDNDState;
@property(retain, nonatomic) NPSManager *npsManager; // @synthesize npsManager=_npsManager;
@property(nonatomic) _Bool isDNDMirrorEnabled; // @synthesize isDNDMirrorEnabled=_isDNDMirrorEnabled;
@property(retain, nonatomic) BLTRemoteObject *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) BBSettingsGateway *settingsGateway; // @synthesize settingsGateway=_settingsGateway;
- (void).cxx_destruct;
- (void)_isChangeToDNDSettingObsoleteAtDate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateSettingsGatewayTo:(_Bool)arg1 changeDate:(id)arg2;
- (void)_transportConnectionStatusChanged:(id)arg1;
- (void)_updateOnBehalfOfAssertActiveWithConnectionStatus:(unsigned long long)arg1 updateObserver:(_Bool)arg2;
- (void)_updateTransportConnectionStatusObserver:(_Bool)arg1;
- (void)_setAssertionOnBehalfOfActive:(_Bool)arg1;
- (void)setDoNotDisturb:(_Bool)arg1 changeDate:(id)arg2 updateSettingsGateway:(_Bool)arg3;
- (void)setPrivilegedSenderTypes:(unsigned long long)arg1;
- (void)setBehaviorOverrides:(id)arg1;
- (void)setBehaviorOverrideStatus:(long long)arg1;
- (void)setBehaviorOverrideTypes:(unsigned long long)arg1 changedDate:(id)arg2;
- (void)removeDNDHandlers;
- (void)setDNDHandlers;
- (void)updateDNDStateChangedByPreferencesSync:(_Bool)arg1;
- (void)updateDNDMirrorState;
- (void)_settingsGatewayReconnected:(id)arg1;
- (void)dealloc;
- (id)initWithSettingsGateway:(id)arg1 connection:(id)arg2 assertionActiveKey:(id)arg3 assertionOnBehalfOfActiveKey:(id)arg4;
- (id)init;

@end

