//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <UserActivity/UASharedPasteboardManagerResponseProtocol-Protocol.h>

@class NSDictionary, NSSet, NSString, NSXPCConnection, UAPasteboardGeneration;
@protocol OS_dispatch_queue;

@interface UASharedPasteboardManager : NSObject <UASharedPasteboardManagerResponseProtocol>
{
    _Bool _remotePasteboardAvaliable;
    _Bool _updateScheduled;
    CDUnknownBlockType _localPasteboardWasFetched;
    UAPasteboardGeneration *_currentGeneration;
    NSObject<OS_dispatch_queue> *_serverQ;
    NSXPCConnection *_connection;
    NSObject<OS_dispatch_queue> *_pasteboardReadQ;
    NSSet *_disallowdTypes;
    NSDictionary *_typeAliases;
    CDUnknownBlockType _completionBlock;
}

+ (_Bool)dontConnectToServer;
+ (id)sharedManager;
+ (void)initialize;
@property CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain) NSDictionary *typeAliases; // @synthesize typeAliases=_typeAliases;
@property(retain) NSSet *disallowdTypes; // @synthesize disallowdTypes=_disallowdTypes;
@property(retain) NSObject<OS_dispatch_queue> *pasteboardReadQ; // @synthesize pasteboardReadQ=_pasteboardReadQ;
@property _Bool updateScheduled; // @synthesize updateScheduled=_updateScheduled;
@property _Bool remotePasteboardAvaliable; // @synthesize remotePasteboardAvaliable=_remotePasteboardAvaliable;
@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain) NSObject<OS_dispatch_queue> *serverQ; // @synthesize serverQ=_serverQ;
@property(retain) UAPasteboardGeneration *currentGeneration; // @synthesize currentGeneration=_currentGeneration;
@property(copy) CDUnknownBlockType localPasteboardWasFetched; // @synthesize localPasteboardWasFetched=_localPasteboardWasFetched;
- (void).cxx_destruct;
- (void)tellClientDebuggingEnabled:(_Bool)arg1 logFileHandle:(id)arg2;
- (void)fetchPasteboardStatus:(CDUnknownBlockType)arg1;
- (void)fetchPasteboardDataForProcess:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)fetchPasteboardTypesForProcess:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)requestRemotePasteboardDataForProcess:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)requestRemotePasteboardTypesForProcess:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)isRemotePasteboardAvaliable;
- (void)writeLocalPasteboardToFile:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)sendUpdateToServer;
- (_Bool)addData:(id)arg1 toItemAtIndex:(unsigned long long)arg2 generation:(unsigned long long)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

