//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKPlaceSectionRowView.h>

@class MKPlaceCardActionItem, NSLayoutConstraint, UIButton;
@protocol MKPlaceCardActionSectionViewDelegate;

__attribute__((visibility("hidden")))
@interface MKPlaceCardActionSectionView : MKPlaceSectionRowView
{
    _Bool _usingSmallFonts;
    NSLayoutConstraint *_heightAnchor;
    NSLayoutConstraint *_leftButtonYConstraint;
    NSLayoutConstraint *_rightButtonYConstraint;
    _Bool _rightAlignSecondItem;
    MKPlaceCardActionItem *_leftItem;
    MKPlaceCardActionItem *_rightItem;
    UIButton *_rightButton;
    UIButton *_leftButton;
    id <MKPlaceCardActionSectionViewDelegate> _delegate;
}

@property(nonatomic) __weak id <MKPlaceCardActionSectionViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) MKPlaceCardActionItem *rightItem; // @synthesize rightItem=_rightItem;
@property(retain, nonatomic) MKPlaceCardActionItem *leftItem; // @synthesize leftItem=_leftItem;
- (void).cxx_destruct;
- (void)_rightButtonIsPressed:(id)arg1;
- (void)_leftButtonIsPressed:(id)arg1;
- (id)_makePlaceActionButtonWithActionItem:(id)arg1 isLeftItem:(_Bool)arg2 useSmallFonts:(_Bool)arg3;
- (void)_contentSizeDidChange;
- (void)tintColorDidChange;
- (void)setTopHairlineHidden:(_Bool)arg1;
- (void)_setUpViewWithButtons;
- (void)dealloc;
- (id)initWithLeftActionItem:(id)arg1 rightActionItem:(id)arg2 useSmallFonts:(_Bool)arg3 rightAlignSecondActionItem:(_Bool)arg4;

@end

