//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchFoundation/SFSearchResult.h>

#import <MapKit/MKLocationManagerObserver-Protocol.h>

@class MKLocationManager, MKMapItem, MKSearchFoundationRichText, NSArray, NSData, NSMutableArray, NSString, SFActionItem, SFImage, SFText;

@interface MKSearchFoundationResult : SFSearchResult <MKLocationManagerObserver>
{
    _Bool _optionSmallerScreen;
    NSData *_mapsData;
    MKMapItem *_mapItem;
    NSString *_distanceString;
    NSString *_temporaryReviewString;
    NSArray *_descriptions;
    MKSearchFoundationRichText *_reviewLineFullText;
    unsigned long long _iconSize;
    unsigned long long _resultType;
    NSString *_bundleID;
    MKLocationManager *_locationManager;
    MKSearchFoundationRichText *_distanceLineFullText;
    NSMutableArray *_secondLineText;
    NSMutableArray *_thirdLineText;
    id _attributionObserver;
    SFText *_title;
    SFImage *_thumbnail;
    SFActionItem *_action;
}

- (void)setAction:(id)arg1;
- (id)action;
- (void)setThumbnail:(id)arg1;
- (id)thumbnail;
- (void)setTitle:(id)arg1;
- (id)title;
@property(retain, nonatomic) id attributionObserver; // @synthesize attributionObserver=_attributionObserver;
@property(nonatomic) _Bool optionSmallerScreen; // @synthesize optionSmallerScreen=_optionSmallerScreen;
@property(copy, nonatomic) NSMutableArray *thirdLineText; // @synthesize thirdLineText=_thirdLineText;
@property(copy, nonatomic) NSMutableArray *secondLineText; // @synthesize secondLineText=_secondLineText;
@property(retain, nonatomic) MKSearchFoundationRichText *distanceLineFullText; // @synthesize distanceLineFullText=_distanceLineFullText;
@property(retain, nonatomic) MKLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(nonatomic) unsigned long long resultType; // @synthesize resultType=_resultType;
@property(nonatomic) unsigned long long iconSize; // @synthesize iconSize=_iconSize;
@property(retain, nonatomic) MKSearchFoundationRichText *reviewLineFullText; // @synthesize reviewLineFullText=_reviewLineFullText;
- (void)setDescriptions:(id)arg1;
- (id)descriptions;
@property(retain, nonatomic) NSString *temporaryReviewString; // @synthesize temporaryReviewString=_temporaryReviewString;
@property(copy, nonatomic) NSString *distanceString; // @synthesize distanceString=_distanceString;
@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
@property(retain, nonatomic) NSData *mapsData; // @synthesize mapsData=_mapsData;
- (void).cxx_destruct;
- (void)locationManager:(id)arg1 didUpdateVehicleHeading:(double)arg2 timestamp:(id)arg3;
- (void)locationManager:(id)arg1 didUpdateVehicleSpeed:(double)arg2 timestamp:(id)arg3;
- (void)locationManagerDidResumeLocationUpdates:(id)arg1;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
- (_Bool)locationManagerShouldPauseLocationUpdates:(id)arg1;
- (void)locationManagerDidReset:(id)arg1;
- (void)locationManagerFailedToUpdateLocation:(id)arg1 withError:(id)arg2;
- (void)locationManagerUpdatedLocation:(id)arg1;
- (_Bool)_isSmallerScreen;
- (id)styledStringFromStringArray:(id)arg1;
- (id)_defaultRichTextItems;
- (void)_commonInit;
- (void)dealloc;
- (id)initWithMapsIndexableFavoriteSpotlightRepresentation:(id)arg1 iconSize:(unsigned long long)arg2 currentLocation:(id)arg3;
- (id)initWithMapItem:(id)arg1 iconSize:(unsigned long long)arg2 currentLocation:(id)arg3;
- (id)initWithMapsData:(id)arg1 iconSize:(unsigned long long)arg2 currentLocation:(id)arg3;
- (id)initWithMapsIndexableFavoriteSpotlightRepresentation:(id)arg1 iconSize:(unsigned long long)arg2 bundleID:(id)arg3;
- (id)initWithMapItem:(id)arg1 iconSize:(unsigned long long)arg2 bundleID:(id)arg3;
- (id)initWithMapsData:(id)arg1 iconSize:(unsigned long long)arg2 bundleID:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

