//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCalendar, NSDate, NSMutableSet, NSString, NTKCharacterResourceLoader, NTKCharacterShader, UIColor, _Arms, _Background, _Body, _Foot, _Head;

@interface NTKCharacterRenderer : NSObject
{
    int _prevState;
    int _idealState;
    int _curState;
    int _endState;
    int _prevPose;
    int _idealPose;
    int _curPose;
    int _endPose;
    float _hourHandPos;
    float _minHandPos;
    unsigned int _curProg;
    unsigned int _curVAO;
    NSMutableSet *_textures;
    NSCalendar *_cal;
    NSDate *_overrideDate;
    float _overrideDateFraction;
    double _fromHourPercent;
    double _fromMinutePercent;
    double _toHourPercent;
    double _toMinutePercent;
    float _animationFrameInterval;
    _Bool _animatingToNewDate;
    _Bool _animatingIntoOrb;
    _Bool _applyInstantTimeWarp;
    _Bool _sayCheese;
    float _scrubOffset;
    _Bool _inTimeTravel;
    NSDate *_timeTravelEnterDate;
    NTKCharacterResourceLoader *_loader;
    struct CharacterPoseSpecs _poseSpecs[2];
    struct CharacterStateSpecs _stateSpecs[4];
    _Bool _active;
    int _modelMatrixLoc;
    int _clothingColorLoc;
    float _zoomScaleMickey;
    float _zoomFraction;
    float _curTimeMod1Sec;
    float _curTimeMod15Sec;
    NSString *_prefix;
    double _brightness;
    double _backgroundBrightness;
    _Head *_head;
    _Body *_body;
    _Foot *_foot;
    _Arms *_arms;
    _Background *_background;
    NTKCharacterShader *_progRGBASimpleSprite;
    NTKCharacterShader *_progAlphaSimpleSprite;
    NTKCharacterShader *_progRGBABoneSprite;
    NTKCharacterShader *_progHeadSprite;
    UIColor *_clothingColor;
    double _desaturation;
    union _GLKVector2 _neckBone;
    union _GLKMatrix4 _headMatrix;
}

+ (id)rendererWithCharacter:(unsigned long long)arg1;
@property(readonly) float curTimeMod15Sec; // @synthesize curTimeMod15Sec=_curTimeMod15Sec;
@property(readonly) float curTimeMod1Sec; // @synthesize curTimeMod1Sec=_curTimeMod1Sec;
@property(readonly) union _GLKVector2 neckBone; // @synthesize neckBone=_neckBone;
@property(readonly) union _GLKMatrix4 headMatrix; // @synthesize headMatrix=_headMatrix;
@property(readonly) float zoomFraction; // @synthesize zoomFraction=_zoomFraction;
@property(readonly) float zoomScaleMickey; // @synthesize zoomScaleMickey=_zoomScaleMickey;
@property(readonly) int clothingColorLoc; // @synthesize clothingColorLoc=_clothingColorLoc;
@property(readonly) int modelMatrixLoc; // @synthesize modelMatrixLoc=_modelMatrixLoc;
@property(readonly) double desaturation; // @synthesize desaturation=_desaturation;
@property(readonly) UIColor *clothingColor; // @synthesize clothingColor=_clothingColor;
@property(readonly) NTKCharacterShader *progHeadSprite; // @synthesize progHeadSprite=_progHeadSprite;
@property(readonly) NTKCharacterShader *progRGBABoneSprite; // @synthesize progRGBABoneSprite=_progRGBABoneSprite;
@property(readonly) NTKCharacterShader *progAlphaSimpleSprite; // @synthesize progAlphaSimpleSprite=_progAlphaSimpleSprite;
@property(readonly) NTKCharacterShader *progRGBASimpleSprite; // @synthesize progRGBASimpleSprite=_progRGBASimpleSprite;
@property(retain) _Background *background; // @synthesize background=_background;
@property(retain) _Arms *arms; // @synthesize arms=_arms;
@property(retain) _Foot *foot; // @synthesize foot=_foot;
@property(retain) _Body *body; // @synthesize body=_body;
@property(retain) _Head *head; // @synthesize head=_head;
@property(nonatomic) double backgroundBrightness; // @synthesize backgroundBrightness=_backgroundBrightness;
@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
@property(readonly, nonatomic) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
- (void).cxx_destruct;
- (int)curPose;
- (int)curState;
- (void)_drawCharacter;
- (void)render;
- (void)_drawMinuteHand;
- (void)_drawHourHand;
- (float)_getElbowScaleForPosition:(float)arg1;
- (void)_drawArmFromShoulder:(union _GLKVector3)arg1 toWrist:(union _GLKVector3)arg2 withBend:(float)arg3;
- (void)_drawHead;
- (void)_drawTappingFoot;
- (void)_lowerFootAfterBodyAnimation;
- (void)_raiseFootForBodyAnimation;
- (void)_updateWaitingForFootRaise;
- (_Bool)_footIsRaisedEnoughToStartAnimation;
- (void)_doneWaitingForFootRaise;
- (void)_applyClothingColor;
- (void)_drawBody;
- (void)_idleBodyAfterAnimation;
- (void)_drawBackground;
- (void)_bindGLVAO:(unsigned int)arg1;
- (void)_updateStateAndPose;
- (void)setScrubOffset:(float)arg1;
- (void)scrubToDate:(id)arg1;
- (void)_resetTimeVariable;
- (void)_updateTimeVariables;
- (void)setupTextures;
- (void)loadShiftTextures;
- (void)loadFootTextures;
- (void)loadHeadBlinkTextures;
- (void)loadHeadTextures;
- (void)loadBodyTextures;
- (void)loadNumbersTexture;
- (void)loadBackgroundTextures;
- (id)textureWithName:(id)arg1;
- (void)setupBodyState;
- (void)setupVAOs;
- (void)setupShaders;
- (void)cleanupAfterZoom;
- (void)setZoomFraction:(double)arg1 diameter:(double)arg2;
- (void)prepareToZoom;
- (void)deactivate;
- (void)activate;
- (void)dealloc;
- (void)localeChanged;
- (void)significantTimeChanged:(id)arg1;
- (void)_setStateSpecs:(struct CharacterStateSpecs [4])arg1;
- (void)_setPoseSpecs:(struct CharacterPoseSpecs [2])arg1;
- (id)initWithCharacter:(unsigned long long)arg1 andLoader:(id)arg2;
- (void)setClothingColor:(id)arg1 andDesaturation:(double)arg2;
- (void)setTimeOffset:(double)arg1;
- (void)cleanupToOverrideDate:(id)arg1;
- (void)setOverrideDateFraction:(double)arg1;
- (void)prepareToAnimateToDate:(id)arg1 forOrb:(_Bool)arg2;
- (void)setAnimationFrameInterval:(float)arg1;

@end

