//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CAEAGLLayer, EAGLContext;

@interface NTKCharacterFrameBuffer : NSObject
{
    EAGLContext *_context;
    unsigned int _defaultFBOName;
    unsigned int _colorRenderbuffer;
    int _viewWidth;
    int _viewHeight;
    int _allocatedWidth;
    int _allocatedHeight;
    CAEAGLLayer *_cachedLayer;
}

- (void).cxx_destruct;
- (void)present;
- (_Bool)resizeFromLayer:(id)arg1;
- (_Bool)resizeFromCachedLayer;
- (void)setupFBOs:(id)arg1;
- (_Bool)valid;
- (id)initWithContext:(id)arg1 andDrawable:(id)arg2;

@end

