//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKColoringImageView.h>

@class UIColor, UIImage, UIImageView;

@interface NTKHandView : NTKColoringImageView
{
    UIImageView *_shadowImageView;
    NTKColoringImageView *_inlayView;
    _Bool _shadowsHidden;
    double _zRotation;
    double _scale;
    UIColor *_inlayColor;
    UIImage *_shadowImage;
    struct CGPoint _shadowAnchorPoint;
    struct UIEdgeInsets _inlayInsets;
    struct UIEdgeInsets _shadowInsets;
}

+ (id)_resizableInlayImage;
@property(nonatomic) struct CGPoint shadowAnchorPoint; // @synthesize shadowAnchorPoint=_shadowAnchorPoint;
@property(retain, nonatomic) UIImage *shadowImage; // @synthesize shadowImage=_shadowImage;
@property(nonatomic) struct UIEdgeInsets shadowInsets; // @synthesize shadowInsets=_shadowInsets;
@property(nonatomic) _Bool shadowsHidden; // @synthesize shadowsHidden=_shadowsHidden;
@property(nonatomic) struct UIEdgeInsets inlayInsets; // @synthesize inlayInsets=_inlayInsets;
@property(retain, nonatomic) UIColor *inlayColor; // @synthesize inlayColor=_inlayColor;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) double zRotation; // @synthesize zRotation=_zRotation;
- (void).cxx_destruct;
- (void)_updateShadows;
- (void)_updateTransform;
@property(readonly, nonatomic) NTKColoringImageView *inlayView;
- (void)layoutSubviews;
- (id)initWithImage:(id)arg1;

@end

