//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GameplayKit/GKAgent.h>

@interface GKAgent3D : GKAgent
{
}

- (void)updateWithDeltaTime:(double)arg1;
// Error parsing type for property rotation:
// Property attributes: T{?=[3]},N

// Error parsing type for property velocity:
// Property attributes: T,R,N

// Error parsing type for property position:
// Property attributes: T,N

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

