//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/GEOServerFormatToken-Protocol.h>
#import <GeoServices/NSCopying-Protocol.h>

@class GEOPBTransitArtwork, GEOPrice, NSArray, NSString;
@protocol GEOServerFormatTokenPriceValue;

@interface GEOFormatArgument : PBCodable <GEOServerFormatToken, NSCopying>
{
    CDStruct_9f2792e4 _valInt3s;
    GEOPBTransitArtwork *_artwork;
    int _format;
    GEOPrice *_price;
    NSString *_token;
    unsigned int _valInt1;
    unsigned int _valInt2;
    struct {
        unsigned int format:1;
        unsigned int valInt1:1;
        unsigned int valInt2:1;
    } _has;
}

@property(retain, nonatomic) GEOPBTransitArtwork *artwork; // @synthesize artwork=_artwork;
@property(retain, nonatomic) GEOPrice *price; // @synthesize price=_price;
@property(nonatomic) unsigned int valInt2; // @synthesize valInt2=_valInt2;
@property(nonatomic) unsigned int valInt1; // @synthesize valInt1=_valInt1;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
- (void)mergeFrom:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
@property(readonly, copy) NSString *description;
- (int)StringAsFormat:(id)arg1;
- (id)formatAsString:(int)arg1;
@property(nonatomic) _Bool hasFormat;
@property(nonatomic) int format; // @synthesize format=_format;
@property(readonly, nonatomic) _Bool hasArtwork;
@property(readonly, nonatomic) _Bool hasPrice;
- (void)setValInt3s:(unsigned int *)arg1 count:(unsigned long long)arg2;
- (unsigned int)valInt3AtIndex:(unsigned long long)arg1;
- (void)addValInt3:(unsigned int)arg1;
- (void)clearValInt3s;
@property(readonly, nonatomic) unsigned int *valInt3s;
@property(readonly, nonatomic) unsigned long long valInt3sCount;
@property(nonatomic) _Bool hasValInt2;
@property(nonatomic) _Bool hasValInt1;
@property(readonly, nonatomic) _Bool hasToken;
- (void)dealloc;
@property(readonly, nonatomic) id <GEOServerFormatTokenPriceValue> priceValue;
@property(readonly, nonatomic) NSString *stringValue;
@property(readonly, nonatomic) NSArray *value3s;
@property(readonly, nonatomic) unsigned int value2;
@property(readonly, nonatomic) unsigned int value1;
@property(readonly, nonatomic) long long type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

