//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOAppConfig, GEOAppState, GEODebugLogMessage, GEODeviceConfig, GEODeviceState, GEOPerformanceLogMessage, GEOUsageLogMessage, NSMutableArray, NSString;

@interface GEOLogMessage : PBCodable <NSCopying>
{
    GEOAppConfig *_appConfig;
    GEOAppState *_appState;
    GEODebugLogMessage *_debugLogMessage;
    GEODeviceConfig *_deviceConfig;
    GEODeviceState *_deviceState;
    NSString *_logFacility;
    NSString *_logMessageString;
    int _logMessageSubType;
    int _logMessageType;
    NSMutableArray *_logMsgEvents;
    GEOPerformanceLogMessage *_perfLogMessage;
    GEOUsageLogMessage *_usageLogMessage;
    struct {
        unsigned int logMessageSubType:1;
        unsigned int logMessageType:1;
    } _has;
}

+ (Class)logMsgEventType;
+ (id)logMessagesForEvent:(id)arg1;
+ (_Bool)logMessageType:(int)arg1 acceptsLogMsgEventType:(int)arg2;
+ (id)acceptedLogMsgEventsForLogMessageType:(int)arg1;
+ (id)acceptedLogMsgEvents;
+ (void)initializeAcceptedLogMsgEventTypes;
@property(retain, nonatomic) GEOPerformanceLogMessage *perfLogMessage; // @synthesize perfLogMessage=_perfLogMessage;
@property(retain, nonatomic) GEOUsageLogMessage *usageLogMessage; // @synthesize usageLogMessage=_usageLogMessage;
@property(retain, nonatomic) GEODebugLogMessage *debugLogMessage; // @synthesize debugLogMessage=_debugLogMessage;
@property(retain, nonatomic) NSMutableArray *logMsgEvents; // @synthesize logMsgEvents=_logMsgEvents;
@property(retain, nonatomic) NSString *logFacility; // @synthesize logFacility=_logFacility;
@property(retain, nonatomic) NSString *logMessageString; // @synthesize logMessageString=_logMessageString;
@property(retain, nonatomic) GEODeviceState *deviceState; // @synthesize deviceState=_deviceState;
@property(retain, nonatomic) GEOAppState *appState; // @synthesize appState=_appState;
@property(retain, nonatomic) GEODeviceConfig *deviceConfig; // @synthesize deviceConfig=_deviceConfig;
@property(retain, nonatomic) GEOAppConfig *appConfig; // @synthesize appConfig=_appConfig;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasPerfLogMessage;
@property(readonly, nonatomic) _Bool hasUsageLogMessage;
@property(readonly, nonatomic) _Bool hasDebugLogMessage;
- (int)StringAsLogMessageSubType:(id)arg1;
- (id)logMessageSubTypeAsString:(int)arg1;
@property(nonatomic) _Bool hasLogMessageSubType;
@property(nonatomic) int logMessageSubType; // @synthesize logMessageSubType=_logMessageSubType;
- (int)StringAsLogMessageType:(id)arg1;
- (id)logMessageTypeAsString:(int)arg1;
@property(nonatomic) _Bool hasLogMessageType;
@property(nonatomic) int logMessageType; // @synthesize logMessageType=_logMessageType;
- (id)logMsgEventAtIndex:(unsigned long long)arg1;
- (unsigned long long)logMsgEventsCount;
- (void)addLogMsgEvent:(id)arg1;
- (void)clearLogMsgEvents;
@property(readonly, nonatomic) _Bool hasLogFacility;
@property(readonly, nonatomic) _Bool hasLogMessageString;
@property(readonly, nonatomic) _Bool hasDeviceState;
@property(readonly, nonatomic) _Bool hasAppState;
@property(readonly, nonatomic) _Bool hasDeviceConfig;
@property(readonly, nonatomic) _Bool hasAppConfig;
- (void)dealloc;
- (unsigned int)groupSequenceNumber;
- (id)groupIdentifier;
- (_Bool)acceptsLogMsgEventType:(int)arg1;

@end

