//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaServices/MSVOperation.h>

@interface _MPStoreLibraryPersonalizationAggregateLibraryAddedOperation : MSVOperation
{
    CDUnknownBlockType _responseHandler;
    shared_ptr_f45adb51 _libraryView;
    vector_c1c297d2 _persistentIDs;
}

@property(copy, nonatomic) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
@property(nonatomic) vector_c1c297d2 persistentIDs; // @synthesize persistentIDs=_persistentIDs;
@property(nonatomic) shared_ptr_f45adb51 libraryView; // @synthesize libraryView=_libraryView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)execute;

@end

