//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MPMLPersistentIDList : NSObject
{
    shared_ptr_47cceffc _persistentIDs;
}

+ (id)listWithPropertyIDs:(shared_ptr_47cceffc)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)enumerateIDsUsingBlock:(CDUnknownBlockType)arg1;
- (long long)persistentIDAtIndex:(long long)arg1;
- (long long)count;

@end

