//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaServices/MSVOperation.h>

@class MPMediaLibraryView, MPModelObject, NSNumber;

@interface MPModelLibraryKeepLocalStatusRequestOperation : MSVOperation
{
    long long _enableState;
    MPModelObject *_identifyingModelObject;
    MPMediaLibraryView *_libraryView;
    NSNumber *_redownloadableItemCount;
    CDUnknownBlockType _responseHandler;
    shared_ptr_34add297 _downloadableItemsQuery;
}

@property(copy, nonatomic) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
@property(copy, nonatomic) NSNumber *redownloadableItemCount; // @synthesize redownloadableItemCount=_redownloadableItemCount;
@property(retain, nonatomic) MPMediaLibraryView *libraryView; // @synthesize libraryView=_libraryView;
@property(retain, nonatomic) MPModelObject *identifyingModelObject; // @synthesize identifyingModelObject=_identifyingModelObject;
@property(nonatomic) long long enableState; // @synthesize enableState=_enableState;
@property(nonatomic) shared_ptr_34add297 downloadableItemsQuery; // @synthesize downloadableItemsQuery=_downloadableItemsQuery;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)execute;

@end

