//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPStoreUserEnvironment.h>

@class NSString;

@interface MPMutableUserStoreEnvironment : MPStoreUserEnvironment
{
}

@property(copy, nonatomic) NSString *storeFrontIdentifier; // @dynamic storeFrontIdentifier;
@property(nonatomic) unsigned long long accountIdentifier; // @dynamic accountIdentifier;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

