//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DCIMAVMetadataUtilities : NSObject
{
}

+ (id)montageStringForAsset:(id)arg1;
+ (id)_captureModeStringFromAssetTrack:(id)arg1;
+ (id)_captureModeStringFromAsset:(id)arg1;
+ (_Bool)isTimelapseAsset:(id)arg1;
+ (id)metadataItemForTimelapse;

@end

