//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <Intents/NSCopying-Protocol.h>

@class NSString, PBUnknownFields, _INPBImageValue, _INPBValueMetadata;

@interface _INPBContactValue : PBCodable <NSCopying>
{
    PBUnknownFields *_unknownFields;
    NSString *_contactIdentifier;
    NSString *_firstName;
    NSString *_fullName;
    NSString *_handle;
    _INPBImageValue *_image;
    NSString *_lastName;
    _INPBValueMetadata *_valueMetadata;
}

+ (id)options;
@property(retain, nonatomic) _INPBImageValue *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *handle; // @synthesize handle=_handle;
@property(retain, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(retain, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(retain, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(retain, nonatomic) _INPBValueMetadata *valueMetadata; // @synthesize valueMetadata=_valueMetadata;
- (void).cxx_destruct;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasImage;
@property(readonly, nonatomic) _Bool hasHandle;
@property(readonly, nonatomic) _Bool hasFullName;
@property(readonly, nonatomic) _Bool hasLastName;
@property(readonly, nonatomic) _Bool hasFirstName;
@property(readonly, nonatomic) _Bool hasValueMetadata;
@property(retain, nonatomic) NSString *contactIdentifier;
@property(readonly, nonatomic) _Bool hasContactIdentifier;

@end

