//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Intents/INCacheableContainer-Protocol.h>
#import <Intents/NSCopying-Protocol.h>
#import <Intents/NSSecureCoding-Protocol.h>

@class INImage, INPriceRange, NSArray, NSDate, NSString, NSUserActivity;

@interface INRideOption : NSObject <INCacheableContainer, NSCopying, NSSecureCoding>
{
    NSString *_identifier;
    NSString *_name;
    NSString *_subtitle;
    NSDate *_estimatedPickupDate;
    INPriceRange *_priceRange;
    NSString *_disclaimerMessage;
    NSArray *_availablePartySizeOptions;
    NSString *_availablePartySizeOptionsSelectionPrompt;
    NSString *_specialPricing;
    INImage *_specialPricingBadgeImage;
    NSArray *_fareLineItems;
    NSUserActivity *_userActivityForBookingInApplication;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSUserActivity *userActivityForBookingInApplication; // @synthesize userActivityForBookingInApplication=_userActivityForBookingInApplication;
@property(copy, nonatomic) NSArray *fareLineItems; // @synthesize fareLineItems=_fareLineItems;
@property(copy, nonatomic) INImage *specialPricingBadgeImage; // @synthesize specialPricingBadgeImage=_specialPricingBadgeImage;
@property(copy, nonatomic) NSString *specialPricing; // @synthesize specialPricing=_specialPricing;
@property(copy, nonatomic) NSString *availablePartySizeOptionsSelectionPrompt; // @synthesize availablePartySizeOptionsSelectionPrompt=_availablePartySizeOptionsSelectionPrompt;
@property(copy, nonatomic) NSArray *availablePartySizeOptions; // @synthesize availablePartySizeOptions=_availablePartySizeOptions;
@property(copy, nonatomic) NSString *disclaimerMessage; // @synthesize disclaimerMessage=_disclaimerMessage;
@property(copy, nonatomic) INPriceRange *priceRange; // @synthesize priceRange=_priceRange;
@property(copy, nonatomic) NSDate *estimatedPickupDate; // @synthesize estimatedPickupDate=_estimatedPickupDate;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithName:(id)arg1 estimatedPickupDate:(id)arg2;
- (id)cacheableObjects;
@property(copy, nonatomic) NSString *identifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

