//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Intents/INIntentResponse.h>

@class NSNumber, _INPBStartPhotoPlaybackIntentResponse;

@interface INStartPhotoPlaybackIntentResponse : INIntentResponse
{
    _INPBStartPhotoPlaybackIntentResponse *_responseMessagePBRepresentation;
}

+ (int)_errorCodeFromCode:(long long)arg1;
+ (long long)_codeFromErrorCode:(int)arg1;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(copy, nonatomic) NSNumber *searchResultsCount;
- (id)_responseMessagePBRepresentation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) long long code;
- (id)initWithBackingStore:(id)arg1;
- (id)initWithCode:(long long)arg1 userActivity:(id)arg2;
- (id)init;

@end

