//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationBarDelegate-Protocol.h>

@class UINavigationBar;

@protocol _UINavigationBarDelegatePrivate <UINavigationBarDelegate>

@optional
- (_Bool)isNavigationBarHidden;
- (_Bool)enableBackButtonDuringTransition;
- (void)_updatePaletteConstraints;
- (void)_updatePalettesWithBlock:(void (^)(_UINavigationControllerPalette *))arg1;
- (void)_navigationBarDidChangeStyle:(UINavigationBar *)arg1;
- (void)navigationBarDidChangeOpacity:(UINavigationBar *)arg1;
- (void)navigationBarDidResizeForPrompt:(UINavigationBar *)arg1;
@end

