//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPopoverPresentationController.h>

__attribute__((visibility("hidden")))
@interface _UISharingViewPresentationController : UIPopoverPresentationController
{
    CDUnknownBlockType _dismissalHandler;
}

@property(copy, nonatomic) CDUnknownBlockType dismissalHandler; // @synthesize dismissalHandler=_dismissalHandler;
- (void).cxx_destruct;
- (void)dismissalTransitionDidEnd:(_Bool)arg1;

@end

