//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface _UISystemSoundPlayer : NSObject
{
    unsigned long long _activationCount;
}

+ (id)systemSoundPlayerWithCoordinateSpace:(id)arg1;
+ (id)systemSoundPlayerWithConfiguration:(id)arg1 coordinateSpace:(id)arg2;
- (void)playSystemSoundsWithDelay:(double)arg1 insideBlock:(CDUnknownBlockType)arg2;
- (void)playThrottledSystemSound:(unsigned int)arg1;
- (void)playSystemSound:(unsigned int)arg1;
@property(readonly, nonatomic, getter=isActive) _Bool active;
- (void)deactivate;
- (void)activateWithCompletionBlock:(CDUnknownBlockType)arg1;

@end

