//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIStatusBarButtonActionItemView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface UIStatusBarReturnToLastAppItemView : UIStatusBarButtonActionItemView
{
    NSString *_returnToAppBundleIdentifier;
}

@property(retain, nonatomic) NSString *returnToAppBundleIdentifier; // @synthesize returnToAppBundleIdentifier=_returnToAppBundleIdentifier;
- (void).cxx_destruct;
- (long long)buttonType;
- (_Bool)updateForNewData:(id)arg1 actions:(int)arg2;
- (id)highlightImage;
- (id)contentsImage;

@end

