//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Parsec/NSCopying-Protocol.h>
#import <Parsec/NSSecureCoding-Protocol.h>

@class NSArray, NSDate, NSNumber, NSString;

@interface PRSRankingProperties : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _isCoreSpotlight;
    _Bool _doesAppSupportCS;
    _Bool _isNSUserActivityResult;
    _Bool _csContinuationSupported;
    _Bool _hasRecentNSUserActivity;
    long long _totalUseCount;
    long long _outgoingCount;
    long long _incomingCount;
    NSString *_snippet;
    NSArray *_keywords;
    NSString *_shortcut;
    NSString *_albumName;
    NSArray *_whereFroms;
    NSArray *_alternateNames;
    NSArray *_resultLanguages;
    long long _countOfRecentNSUserActivity;
    NSString *_contentType;
    NSDate *_lastUsedDate;
    NSString *_subject;
    NSString *_authors;
    NSString *_title;
    NSString *_domainIdentifier;
    NSNumber *_latitude;
    NSNumber *_longitude;
    NSDate *_interestingDate;
    double _modelScore;
    double _textMatchQualityScore;
    NSArray *_recipients;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(nonatomic) double textMatchQualityScore; // @synthesize textMatchQualityScore=_textMatchQualityScore;
@property(nonatomic) double modelScore; // @synthesize modelScore=_modelScore;
@property(retain, nonatomic) NSDate *interestingDate; // @synthesize interestingDate=_interestingDate;
@property(retain, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *domainIdentifier; // @synthesize domainIdentifier=_domainIdentifier;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *authors; // @synthesize authors=_authors;
@property(retain, nonatomic) NSString *subject; // @synthesize subject=_subject;
@property(retain, nonatomic) NSDate *lastUsedDate; // @synthesize lastUsedDate=_lastUsedDate;
@property(retain, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(nonatomic) long long countOfRecentNSUserActivity; // @synthesize countOfRecentNSUserActivity=_countOfRecentNSUserActivity;
@property(retain, nonatomic) NSArray *resultLanguages; // @synthesize resultLanguages=_resultLanguages;
@property(retain, nonatomic) NSArray *alternateNames; // @synthesize alternateNames=_alternateNames;
@property(retain, nonatomic) NSArray *whereFroms; // @synthesize whereFroms=_whereFroms;
@property(retain, nonatomic) NSString *albumName; // @synthesize albumName=_albumName;
@property(retain, nonatomic) NSString *shortcut; // @synthesize shortcut=_shortcut;
@property(retain, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) NSString *snippet; // @synthesize snippet=_snippet;
@property(nonatomic) long long incomingCount; // @synthesize incomingCount=_incomingCount;
@property(nonatomic) long long outgoingCount; // @synthesize outgoingCount=_outgoingCount;
@property(nonatomic) long long totalUseCount; // @synthesize totalUseCount=_totalUseCount;
@property _Bool hasRecentNSUserActivity; // @synthesize hasRecentNSUserActivity=_hasRecentNSUserActivity;
@property _Bool csContinuationSupported; // @synthesize csContinuationSupported=_csContinuationSupported;
@property _Bool isNSUserActivityResult; // @synthesize isNSUserActivityResult=_isNSUserActivityResult;
@property _Bool doesAppSupportCS; // @synthesize doesAppSupportCS=_doesAppSupportCS;
@property _Bool isCoreSpotlight; // @synthesize isCoreSpotlight=_isCoreSpotlight;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

