//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotoLibraryServices/PLManagedObject.h>

#import <PhotoLibraryServices/PLSyncableDetectedFace-Protocol.h>

@class NSDate, NSSet, NSString, PLDetectedFaceGroup, PLDetectedFaceprint, PLManagedAsset, PLPerson;

@interface PLDetectedFace : PLManagedObject <PLSyncableDetectedFace>
{
}

+ (long long)resetAssetForAllSyncableFacesInManagedObjectContext:(id)arg1 error:(id *)arg2;
+ (id)_allSyncableFacesInManagedObjectContext:(id)arg1;
+ (id)userCuratedFacePredicate;
+ (id)detectedFaceWithUUID:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (id)findExistingFaceMatchingRef:(id)arg1 inFaces:(id)arg2 inAsset:(id)arg3;
- (id)debugLogDescription;
- (void)removeFaceprint;
- (void)willSave;
- (void)delete;
- (void)awakeFromInsert;
@property(retain, nonatomic) NSSet *rejectedPeople;
@property(nonatomic) _Bool nameSourceAuto;

// Remaining properties
@property(retain, nonatomic) NSDate *adjustmentVersion; // @dynamic adjustmentVersion;
@property(retain, nonatomic) PLManagedAsset *asset; // @dynamic asset;
@property(nonatomic) double centerX; // @dynamic centerX;
@property(nonatomic) double centerY; // @dynamic centerY;
@property(nonatomic) short cloudLocalState; // @dynamic cloudLocalState;
@property(nonatomic) long long clusterSequenceNumber; // @dynamic clusterSequenceNumber;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) double expressionConfidence; // @dynamic expressionConfidence;
@property(nonatomic) double expressionScore1; // @dynamic expressionScore1;
@property(nonatomic) double expressionScore2; // @dynamic expressionScore2;
@property(nonatomic) double expressionScore3; // @dynamic expressionScore3;
@property(nonatomic) long long expressionType1; // @dynamic expressionType1;
@property(nonatomic) long long expressionType2; // @dynamic expressionType2;
@property(nonatomic) long long expressionType3; // @dynamic expressionType3;
@property(nonatomic) long long faceAlgorithmVersion; // @dynamic faceAlgorithmVersion;
@property(retain, nonatomic) PLDetectedFaceGroup *faceGroupBeingKeyFace; // @dynamic faceGroupBeingKeyFace;
@property(retain, nonatomic) NSSet *faceGroups; // @dynamic faceGroups;
@property(retain, nonatomic) PLDetectedFaceprint *faceprint; // @dynamic faceprint;
@property(nonatomic) _Bool hasSmile; // @dynamic hasSmile;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool hidden; // @dynamic hidden;
@property(nonatomic) _Bool isBlurred; // @dynamic isBlurred;
@property(nonatomic) _Bool isHiddenInGroups; // @dynamic isHiddenInGroups;
@property(nonatomic) _Bool isInTrash; // @dynamic isInTrash;
@property(nonatomic) _Bool isLeftEyeClosed; // @dynamic isLeftEyeClosed;
@property(nonatomic) _Bool isRightEyeClosed; // @dynamic isRightEyeClosed;
@property(nonatomic) double leftEyeX; // @dynamic leftEyeX;
@property(nonatomic) double leftEyeY; // @dynamic leftEyeY;
@property(nonatomic) _Bool manual; // @dynamic manual;
@property(retain, nonatomic) NSString *masterIdentifier; // @dynamic masterIdentifier;
@property(nonatomic) double mouthX; // @dynamic mouthX;
@property(nonatomic) double mouthY; // @dynamic mouthY;
@property(nonatomic) int nameSource; // @dynamic nameSource;
@property(retain, nonatomic) PLPerson *person; // @dynamic person;
@property(retain, nonatomic) PLPerson *personBeingKeyFace; // @dynamic personBeingKeyFace;
@property(nonatomic) double posePitch; // @dynamic posePitch;
@property(nonatomic) double poseRoll; // @dynamic poseRoll;
@property(nonatomic) double poseYaw; // @dynamic poseYaw;
@property(nonatomic) long long qualityMeasure; // @dynamic qualityMeasure;
@property(nonatomic) double rightEyeX; // @dynamic rightEyeX;
@property(nonatomic) double rightEyeY; // @dynamic rightEyeY;
@property(nonatomic) double size; // @dynamic size;
@property(nonatomic) long long sourceHeight; // @dynamic sourceHeight;
@property(nonatomic) long long sourceWidth; // @dynamic sourceWidth;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *uuid; // @dynamic uuid;

@end

