//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <PhotoLibraryServices/NSCoding-Protocol.h>

@class NSString;

@interface PLPersistedPersonFaceMetadata : NSObject <NSCoding>
{
    _Bool _hidden;
    _Bool _manual;
    _Bool _representative;
    _Bool _hiddenInGroups;
    _Bool _nameSourceAuto;
    _Bool _isHidden;
    NSString *_assetUUID;
    double _centerX;
    double _centerY;
    double _size;
}

+ (id)persistedFaceMetadataWithDetectedFace:(id)arg1 isKeyFace:(_Bool)arg2;
+ (id)detectedFaceRelationshipKeyPathsToPrefetch;
+ (id)detectedFacePropertiesToFetch;
@property(readonly, nonatomic, getter=isHidden) _Bool isHidden; // @synthesize isHidden=_isHidden;
@property(nonatomic, getter=isNameSourceAuto) _Bool nameSourceAuto; // @synthesize nameSourceAuto=_nameSourceAuto;
@property(nonatomic, getter=isHiddenInGroups) _Bool hiddenInGroups; // @synthesize hiddenInGroups=_hiddenInGroups;
@property(nonatomic, getter=isRepresentative) _Bool representative; // @synthesize representative=_representative;
@property(nonatomic, getter=isManual) _Bool manual; // @synthesize manual=_manual;
@property(nonatomic, getter=isHidden) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) double size; // @synthesize size=_size;
@property(nonatomic) double centerY; // @synthesize centerY=_centerY;
@property(nonatomic) double centerX; // @synthesize centerX=_centerX;
@property(retain, nonatomic) NSString *assetUUID; // @synthesize assetUUID=_assetUUID;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

