//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SiriUI/SiriUITemplateModel-Protocol.h>

@class NSString;

@protocol SiriUITemplateModelPrivate <SiriUITemplateModel>
@property(readonly, copy, nonatomic) NSString *commandIdentifier;
@property(readonly, copy, nonatomic) NSString *detailIdentifier;
@property(readonly, copy, nonatomic) NSString *modelIdentifier;
@end

