//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMWorkout, CMWorkoutManager;
@protocol CMWorkoutManagerDelegate, OS_dispatch_queue, OS_dispatch_source;

@interface CMWorkoutManagerInternal : NSObject
{
    struct CLConnectionClient *fLocationdConnection;
    NSObject<OS_dispatch_queue> *fInternalQueue;
    NSObject<OS_dispatch_source> *fWatchdogTimer;
    id <CMWorkoutManagerDelegate> fDelegate;
    CMWorkoutManager *fSender;
    CMWorkout *fWorkout;
    _Bool fResumeWorkoutOnInterrupt;
}

- (id)_getExecutablePathFromPid:(int)arg1;
- (void)_stopWatchdogCheckins;
- (void)_startWatchdogCheckins;
- (void)_registerForWorkoutEvents;
- (void)_handleDaemonEvent:(id)arg1;
- (void)_handleDaemonResponse:(id)arg1;
- (void)_stopWorkout:(id)arg1;
- (void)_startWorkout:(id)arg1;
- (void)_teardown;
- (void)dealloc;
- (id)init;

@end

