//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreMotion/NSCopying-Protocol.h>
#import <CoreMotion/NSSecureCoding-Protocol.h>

@class NSUUID;

@interface CMWorkout : NSObject <NSSecureCoding, NSCopying>
{
    NSUUID *fSessionId;
    unsigned long long fType;
}

+ (unsigned long long)workoutTypeFromNatalieDataSession:(long long)arg1;
+ (long long)natalieDataSessionFromWorkoutType:(unsigned long long)arg1;
+ (id)workoutName:(unsigned long long)arg1;
+ (_Bool)supportsSecureCoding;
- (id)description;
@property(readonly, nonatomic) unsigned long long type;
@property(readonly, nonatomic) NSUUID *sessionId;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithSessionId:(id)arg1 type:(unsigned long long)arg2;

@end

