//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CacheDelete/CacheDeleteRecent.h>

#import <CacheDelete/NSCopying-Protocol.h>
#import <CacheDelete/NSSecureCoding-Protocol.h>

@class NSMutableDictionary;

@interface CacheDeleteRecentInfo : CacheDeleteRecent <NSSecureCoding, NSCopying>
{
    NSMutableDictionary *_volumes;
}

+ (id)cacheDeleteRecentInfo:(id)arg1;
+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSMutableDictionary *volumes; // @synthesize volumes=_volumes;
- (void).cxx_destruct;
- (void)invalidateForVolume:(id)arg1;
- (void)log;
- (id)lookupAmountForService:(id)arg1 onVolume:(id)arg2 atUrgency:(id)arg3;
- (void)updateDiagnostics:(id)arg1 forVolume:(id)arg2 atUrgency:(id)arg3;
- (id)diagnosticsForVolume:(id)arg1 atUrgency:(id)arg2;
- (void)updateDiagnostics:(id)arg1 forService:(id)arg2 onVolume:(id)arg3 atUrgency:(id)arg4;
- (id)diagnosticsForService:(id)arg1 onVolume:(id)arg2 atUrgency:(id)arg3;
- (_Bool)updateServiceInfoAmount:(id)arg1 forService:(id)arg2 onVolume:(id)arg3 atUrgency:(id)arg4 pushed:(_Bool)arg5;
- (void)removeServiceInfo:(id)arg1;
- (id)recentInfoForVolume:(id)arg1 atUrgency:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)copyInvalidsForVolume:(id)arg1;
- (_Bool)validateForVolume:(id)arg1 andService:(id)arg2;
- (id)initWithVolumes:(id)arg1;

@end

