//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosPlayer/ISLivePhotoPlaybackFilter.h>

@interface ISTouchLivePhotoPlaybackFilter : ISLivePhotoPlaybackFilter
{
    _Bool _touchActive;
    long long __playbackRequestID;
}

@property(nonatomic, setter=_setPlaybackReaquestID:) long long _playbackRequestID; // @synthesize _playbackRequestID=__playbackRequestID;
@property(nonatomic, getter=isTouchActive) _Bool touchActive; // @synthesize touchActive=_touchActive;
- (void)_stopPlayback;
- (void)_startPlaybackWithRequestID:(long long)arg1;
- (void)_startPlaybackAfterDelay;
- (void)inputDidChange;
- (long long)_nextPlaybackRequestID;

@end

