//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudKit/CKRecordID.h>

@interface CKRecordID (BRCItemAdditions)
- (BOOL)brc_itemType;
- (id)brc_itemIDOfTargetWithLibraryRowID:(id)arg1 session:(id)arg2;
- (id)brc_itemIDWithSession:(id)arg1;
- (_Bool)brc_isZoneRootRecordID;
- (id)brc_appLibraryDocumentsZoneName;
- (_Bool)brc_isAppLibraryDocumentsRecordID;
- (id)brc_appLibraryRootZoneName;
- (_Bool)brc_isAppLibraryRootRecordID;
@end

