//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class HMCameraSource;

@interface HMCameraView : UIView
{
    HMCameraSource *_cameraSource;
}

@property(retain, nonatomic) HMCameraSource *cameraSource; // @synthesize cameraSource=_cameraSource;
- (void).cxx_destruct;
- (double)angleForOrientation:(id)arg1;

@end

