//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SFDeviceDiscovery;
@protocol TRNearbyServicesScannerDelegate;

@interface TRNearbyServicesScanner : NSObject
{
    id <TRNearbyServicesScannerDelegate> _delegate;
    SFDeviceDiscovery *_deviceDiscovery;
}

+ (unsigned long long)state;
+ (id)sharedInstance;
+ (void)initialize;
@property(retain, nonatomic) SFDeviceDiscovery *deviceDiscovery; // @synthesize deviceDiscovery=_deviceDiscovery;
@property(nonatomic) __weak id <TRNearbyServicesScannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_deviceLost:(id)arg1;
- (void)_deviceFound:(id)arg1;
- (void)_handleInvalidation;
- (void)_handleActivationWithError:(id)arg1;
- (void)stopScanningForNearbyDevicesNeedingSetup;
- (void)startScanningForNearbyDevicesNeedingSetup;

@end

