//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <MobileCoreServices/NSCopying-Protocol.h>
#import <MobileCoreServices/NSSecureCoding-Protocol.h>

@class NSString;

@interface _LSApplicationState : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_bundleIdentifier;
    unsigned long long _stateFlags;
    int _ratingRank;
}

+ (_Bool)supportsSecureCoding;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)addStateFlag:(unsigned long long)arg1;
- (id)description;
@property(readonly, nonatomic) _Bool isBlocked;
@property(readonly, nonatomic) _Bool isRemovedSystemApp;
@property(readonly, nonatomic) _Bool isRestricted;
@property(readonly, nonatomic) _Bool isInstalled;
@property(readonly, nonatomic) _Bool isPlaceholder;
@property(readonly, nonatomic) _Bool isValid;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1 stateFlags:(unsigned long long)arg2 ratingRank:(int)arg3;

@end

