//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSURL;
@protocol OS_dispatch_queue;

@interface _LSDefaults : NSObject
{
    NSObject<OS_dispatch_queue> *_ivarQueue;
    NSURL *_systemContainerURL;
    NSURL *_systemGroupContainerURL;
    NSURL *_iconsGroupContainerURL;
    NSURL *_userContainerURL;
    _Bool _inSyncBubble;
    _Bool _inXCTestRigInsecure;
    _Bool _isServer;
    _Bool _hasServer;
    _Bool _inEducationMode;
    _Bool _hasPersistentPreferences;
}

+ (_Bool)hasPersistentPreferences;
+ (_Bool)hasServer;
+ (_Bool)inXCTestRigInsecure;
+ (_Bool)inSyncBubble;
+ (id)userContainerURL;
+ (id)iconsGroupContainerURL;
+ (id)systemGroupContainerURL;
+ (id)systemContainerURL;
+ (id)sharedInstance;
@property(readonly) _Bool hasPersistentPreferences; // @synthesize hasPersistentPreferences=_hasPersistentPreferences;
@property(readonly, getter=isInEducationMode) _Bool inEducationMode; // @synthesize inEducationMode=_inEducationMode;
@property _Bool isServer; // @synthesize isServer=_isServer;
@property(readonly, nonatomic, getter=isInXCTestRigInsecure) _Bool inXCTestRigInsecure; // @synthesize inXCTestRigInsecure=_inXCTestRigInsecure;
@property(readonly, getter=isInSyncBubble) _Bool inSyncBubble; // @synthesize inSyncBubble=_inSyncBubble;
- (id)debugDescription;
@property(readonly) double databaseSaveLatency;
@property(readonly) double databaseSaveInterval;
- (id)preferencesFileChangeNotificationName;
- (id)preferencesUpdateNotificationName;
- (id)databaseUpdateNotificationName;
- (id)darwinNotificationNameForCurrentUser:(id)arg1;
- (unsigned int)proxyUIDForUID:(unsigned int)arg1;
@property(readonly) _Bool isSimulator;
- (id)serviceNameForConnectionType:(unsigned short)arg1;
@property _Bool hasServer; // @synthesize hasServer=_hasServer;
@property(readonly) NSURL *dbSentinelFileURL;
@property(readonly) NSURL *iconCacheSystemVersionFileURL;
@property(readonly) NSURL *iconCacheFolderURL;
@property(readonly) NSURL *identifiersFileURL;
@property(readonly) NSURL *queriedSchemesMapFileURL;
@property(readonly) NSURL *securePeferencesFileURL;
@property(readonly) NSURL *preferencesFileURL;
@property(readonly) NSURL *databaseStoreFileURL;
- (id)userPreferencesURL;
@property(readonly) NSURL *iconsGroupContainerURL;
@property(readonly) NSURL *systemGroupContainerURL;
@property(readonly) NSURL *userContainerURL;
@property(readonly) NSURL *systemContainerURL;
@property(readonly) unsigned int currentSchemaVersion;
- (void)dealloc;
- (id)init;

@end

