//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SearchUI/SearchUIResult-Protocol.h>

@class NSArray, NSString, NSURL, SFSearchResult, UIImage;
@protocol SearchUIActionButtonItem, SearchUIAuxiliaryInfo;

@interface SearchUIResult : NSObject <SearchUIResult>
{
    _Bool _secondaryTitleDetached;
    _Bool _isScrollable;
    _Bool _centered;
    _Bool _shouldCropImageToCircle;
    _Bool _supportsActions;
    _Bool _isLocalApplicationResult;
    _Bool _preventImageScaling;
    UIImage *_image;
    double _imageCornerRadius;
    NSString *_title;
    NSString *_secondaryTitle;
    UIImage *_secondaryImage;
    NSString *_sectionTitle;
    unsigned long long _titleMaxLines;
    long long _titleSize;
    long long _titleWeight;
    NSArray *_richTextItems;
    NSString *_footnote;
    id <SearchUIActionButtonItem> _actionButton;
    id <SearchUIAuxiliaryInfo> _auxiliaryInfo;
    NSArray *_cardSections;
    NSURL *_cardURL;
    NSArray *_rowSections;
    NSURL *_destinationURL;
    NSString *_contactIdentifier;
    UIImage *_embeddedThumbnailImage;
    NSString *_bundleID;
    NSString *_calendarIdentifier;
    SFSearchResult *_sfSearchResult;
}

@property(retain, nonatomic) SFSearchResult *sfSearchResult; // @synthesize sfSearchResult=_sfSearchResult;
@property(nonatomic) _Bool preventImageScaling; // @synthesize preventImageScaling=_preventImageScaling;
@property(nonatomic) _Bool isLocalApplicationResult; // @synthesize isLocalApplicationResult=_isLocalApplicationResult;
@property(copy, nonatomic) NSString *calendarIdentifier; // @synthesize calendarIdentifier=_calendarIdentifier;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(copy, nonatomic) UIImage *embeddedThumbnailImage; // @synthesize embeddedThumbnailImage=_embeddedThumbnailImage;
@property(nonatomic) _Bool supportsActions; // @synthesize supportsActions=_supportsActions;
@property(copy, nonatomic) NSString *contactIdentifier; // @synthesize contactIdentifier=_contactIdentifier;
@property(copy, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(nonatomic) _Bool shouldCropImageToCircle; // @synthesize shouldCropImageToCircle=_shouldCropImageToCircle;
@property(nonatomic) _Bool centered; // @synthesize centered=_centered;
@property(copy, nonatomic) NSArray *rowSections; // @synthesize rowSections=_rowSections;
@property(copy, nonatomic) NSURL *cardURL; // @synthesize cardURL=_cardURL;
@property(copy, nonatomic) NSArray *cardSections; // @synthesize cardSections=_cardSections;
@property(retain, nonatomic) id <SearchUIAuxiliaryInfo> auxiliaryInfo; // @synthesize auxiliaryInfo=_auxiliaryInfo;
@property(retain, nonatomic) id <SearchUIActionButtonItem> actionButton; // @synthesize actionButton=_actionButton;
@property(copy, nonatomic) NSString *footnote; // @synthesize footnote=_footnote;
@property(retain, nonatomic) NSArray *richTextItems; // @synthesize richTextItems=_richTextItems;
@property(nonatomic) _Bool isScrollable; // @synthesize isScrollable=_isScrollable;
@property(nonatomic) long long titleWeight; // @synthesize titleWeight=_titleWeight;
@property(nonatomic) long long titleSize; // @synthesize titleSize=_titleSize;
@property(nonatomic) unsigned long long titleMaxLines; // @synthesize titleMaxLines=_titleMaxLines;
@property(nonatomic) _Bool secondaryTitleDetached; // @synthesize secondaryTitleDetached=_secondaryTitleDetached;
@property(copy, nonatomic) NSString *sectionTitle; // @synthesize sectionTitle=_sectionTitle;
@property(retain, nonatomic) UIImage *secondaryImage; // @synthesize secondaryImage=_secondaryImage;
@property(copy, nonatomic) NSString *secondaryTitle; // @synthesize secondaryTitle=_secondaryTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double imageCornerRadius; // @synthesize imageCornerRadius=_imageCornerRadius;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool requiresTwoLineTitles;
@property(readonly) Class superclass;

@end

