//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SFMediaInfoCardSection, SFPunchout, SKUIItemOfferButton, SearchUICardViewController, UILabel;

@interface SearchUIMovieCardSectionBuyButtonView : UIView
{
    UILabel *_subtitleLabel;
    SKUIItemOfferButton *_button;
    SFPunchout *_punchout;
    SearchUICardViewController *_controller;
    SFMediaInfoCardSection *_section;
}

@property(retain) SFMediaInfoCardSection *section; // @synthesize section=_section;
@property __weak SearchUICardViewController *controller; // @synthesize controller=_controller;
@property(retain) SFPunchout *punchout; // @synthesize punchout=_punchout;
@property(retain) SKUIItemOfferButton *button; // @synthesize button=_button;
@property(retain) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)buttonPressed;
- (void)lookupPriceForAdamID:(id)arg1 offerIdentifier:(id)arg2;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 punchout:(id)arg3 adamID:(id)arg4 offerIdentifier:(id)arg5 controller:(id)arg6 section:(id)arg7;

@end

