//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchUI/SearchUICardSection.h>

#import <SearchUI/SearchUITwitterCardSection-Protocol.h>

@class NSArray, NSString, NSURL, UIImage;
@protocol SearchUIRichTextItem;

@interface SearchUITwitterCardSection : SearchUICardSection <SearchUITwitterCardSection>
{
    NSString *_title;
    NSString *_subtitle;
    UIImage *_userThumbnail;
    UIImage *_tweetImage;
    UIImage *_verifiedImage;
    id <SearchUIRichTextItem> _tweet;
    NSString *_date;
    NSString *_footnote;
}

@property(copy, nonatomic) NSString *footnote; // @synthesize footnote=_footnote;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
@property(retain, nonatomic) id <SearchUIRichTextItem> tweet; // @synthesize tweet=_tweet;
@property(retain, nonatomic) UIImage *verifiedImage; // @synthesize verifiedImage=_verifiedImage;
@property(retain, nonatomic) UIImage *tweetImage; // @synthesize tweetImage=_tweetImage;
@property(retain, nonatomic) UIImage *userThumbnail; // @synthesize userThumbnail=_userThumbnail;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool hasBottomPadding;
@property(readonly, nonatomic) _Bool hasTopPadding;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool hideDivider;
@property(readonly, nonatomic) NSArray *punchoutOptions;
@property(readonly, nonatomic) NSString *punchoutPickerDismissLabel;
@property(readonly, nonatomic) NSString *punchoutPickerLabel;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSString *type;
@property(readonly, copy, nonatomic) NSURL *url;

@end

