//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchUIFoundation/SearchUIAppIconImage.h>

@interface SearchUIAppIconImage (SearchUI)
+ (double)cornerRadiusForHomeScreenIcons;
+ (struct CGRect)visibleFrameForSmallSpotlightIcons;
+ (struct CGRect)visibleFrameForHomeScreenIcons;
+ (struct CGSize)homeScreenIconSize;
- (id)generateImageWithFormat:(int)arg1;
- (id)loadImage;
- (void)setSize;
@end

