//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SearchUI/SearchUIAuxiliaryInfo-Protocol.h>

@class NSString;

@interface SearchUIAuxiliaryInfo : NSObject <SearchUIAuxiliaryInfo>
{
    NSString *_topText;
    NSString *_middleText;
    NSString *_bottomText;
    NSString *_bottomTextColor;
}

@property(copy, nonatomic) NSString *bottomTextColor; // @synthesize bottomTextColor=_bottomTextColor;
@property(copy, nonatomic) NSString *bottomText; // @synthesize bottomText=_bottomText;
@property(copy, nonatomic) NSString *middleText; // @synthesize middleText=_middleText;
@property(copy, nonatomic) NSString *topText; // @synthesize topText=_topText;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

