//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNContactStore, NSCache;

@interface SearchUIContactStore : NSObject
{
    NSCache *_contactCache;
    CNContactStore *_contactStore;
}

+ (id)imageForContact:(id)arg1 style:(unsigned long long)arg2;
+ (id)placeholderContact;
+ (id)contactForPhoneNumber:(id)arg1;
+ (id)sharedStore;
@property(retain) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(retain) NSCache *contactCache; // @synthesize contactCache=_contactCache;
- (void).cxx_destruct;
- (void)fetchContactForIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)cachedContactForIdentifier:(id)arg1;
- (id)init;

@end

