//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UpNextWidget/_TtC12UpNextWidget14GutterizedView.h>

@class NSDate, UIView;

@interface _TtC12UpNextWidget16SmallSummaryView : _TtC12UpNextWidget14GutterizedView
{
    // Error parsing type: , name: allHappenToday
    // Error parsing type: , name: allHappenTomorrow
    // Error parsing type: , name: numberOfEvents
    // Error parsing type: , name: time
    // Error parsing type: , name: label
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)viewForLastBaselineLayout;
@property(nonatomic, retain) NSDate *time; // @synthesize time;
@property(nonatomic) _Bool allHappenTomorrow; // @synthesize allHappenTomorrow;
@property(nonatomic) _Bool allHappenToday; // @synthesize allHappenToday;

// Remaining properties
@property(nonatomic, readonly) UIView *forLastBaselineLayout;

@end

