//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UpNextWidget/_TtC12UpNextWidget14GutterizedView.h>

@class NSAttributedString, UIView;

@interface _TtC12UpNextWidget18TravelAdvisoryView : _TtC12UpNextWidget14GutterizedView
{
    // Error parsing type: , name: travelAdvisoryText
    // Error parsing type: , name: label
    // Error parsing type: , name: arrowImageView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)viewForLastBaselineLayout;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, retain) NSAttributedString *travelAdvisoryText; // @synthesize travelAdvisoryText;

// Remaining properties
@property(nonatomic, readonly) UIView *forLastBaselineLayout;

@end

