//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <UpNextWidget/NCWidgetProviding-Protocol.h>

@interface _TtC12UpNextWidget21TestingViewController : UIViewController <NCWidgetProviding>
{
    // Error parsing type: , name: testingView
    // Error parsing type: , name: showExpandedMode
}

- (CDUnknownBlockType).cxx_destruct;
- (void)widgetActiveDisplayModeDidChangeWithActiveDisplayMode:(long long)arg1 withMaximumSize:(struct CGSize)arg2;
- (void)widgetPerformUpdateWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool showExpandedMode; // @synthesize showExpandedMode;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

