//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class EKTravelEngineHypothesis, UIImage;

@interface _TtC12UpNextWidget22DetailedViewController : UIViewController
{
    // Error parsing type: , name: showExpandedMode
    // Error parsing type: , name: detailedView
    // Error parsing type: , name: largeEventView
    // Error parsing type: , name: largeReminderView
    // Error parsing type: , name: smallElementsView
    // Error parsing type: , name: lastKnownHypothesis
    // Error parsing type: , name: lastKnownMapImage
    // Error parsing type: , name: outstandingHypothesizer
    // Error parsing type: , name: outstandingSnapshotter
    // Error parsing type: , name: previousSize
}

- (CDUnknownBlockType).cxx_destruct;
- (void)refreshWithAlarms:(id)arg1 events:(id)arg2 reminders:(id)arg3;
- (void)loadView;
- (void)systemLayoutFittingSizeDidChangeForChildContentContainer:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)restoreWithHypothesis:(id)arg1 mapImage:(id)arg2;
@property(nonatomic, retain) UIImage *lastKnownMapImage; // @synthesize lastKnownMapImage;
@property(nonatomic, retain) EKTravelEngineHypothesis *lastKnownHypothesis; // @synthesize lastKnownHypothesis;
@property(nonatomic) _Bool showExpandedMode; // @synthesize showExpandedMode;

@end

