//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface PKTray : NSObject
{
    NSDictionary *_trayDict;
}

+ (id)trayWithString:(id)arg1 andMediaSource:(id)arg2;
+ (id)filter:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
+ (id)traysWithAttrs:(struct _ipp_s *)arg1;
@property(retain) NSDictionary *trayDict; // @synthesize trayDict=_trayDict;
- (id)description;
@property(readonly) _Bool isEmpty; // @dynamic isEmpty;
@property(readonly) NSString *localizedName;
@property(readonly) NSString *name; // @dynamic name;
- (id)initWithString:(id)arg1 andMediaSource:(id)arg2;

@end

