//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CVML/CVMLDetector.h>

@protocol CVMLModelFile;

@interface CVMLFaceBBoxAligner : CVMLDetector
{
    struct shared_ptr<vision::mod::FaceboxAligner> mFaceBoxAlignerImpl;
    id <CVMLModelFile> mFaceBoxAlignerModelFileHandle;
}

+ (_Bool)shouldDumpDebugIntermediates;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)processWithOptions:(id)arg1 warningRecorder:(id)arg2 cancellationSemaphore:(id)arg3 error:(id *)arg4;
- (void)dealloc;
- (id)initWithOptions:(id)arg1 error:(id *)arg2;

@end

