//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Sharing/SFPeerDevice.h>

#import <Sharing/NSSecureCoding-Protocol.h>

@class NSDictionary, NSString, NSUUID;

@interface SFAutoUnlockDevice : SFPeerDevice <NSSecureCoding>
{
    _Bool _unlockEnabled;
    _Bool _keyExists;
    NSUUID *_bluetoothID;
    NSUUID *_proxyBluetoothID;
    NSString *_modelName;
    NSDictionary *_results;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSDictionary *results; // @synthesize results=_results;
@property(retain, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
@property(copy, nonatomic) NSUUID *proxyBluetoothID; // @synthesize proxyBluetoothID=_proxyBluetoothID;
@property(retain, nonatomic) NSUUID *bluetoothID; // @synthesize bluetoothID=_bluetoothID;
@property(nonatomic) _Bool keyExists; // @synthesize keyExists=_keyExists;
@property(nonatomic) _Bool unlockEnabled; // @synthesize unlockEnabled=_unlockEnabled;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
@property(readonly, nonatomic) long long type;

@end

