//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import <PhotosUICore/PXPeopleDataSourceDelegate-Protocol.h>
#import <PhotosUICore/UICollectionViewDataSourcePrefetching-Protocol.h>
#import <PhotosUICore/UICollectionViewDelegateFlowLayout-Protocol.h>

@class NSString, PXPeoplePersonDataSource, UIBarButtonItem;

@interface PXPeopleAddViewController : UICollectionViewController <UICollectionViewDelegateFlowLayout, UICollectionViewDataSourcePrefetching, PXPeopleDataSourceDelegate>
{
    UIBarButtonItem *_cancelItem;
    UIBarButtonItem *_addItem;
    PXPeoplePersonDataSource *_dataSource;
    struct CGSize _priorityItemSize;
    struct CGSize _nonPriorityItemSize;
}

@property struct CGSize nonPriorityItemSize; // @synthesize nonPriorityItemSize=_nonPriorityItemSize;
@property struct CGSize priorityItemSize; // @synthesize priorityItemSize=_priorityItemSize;
@property(retain) PXPeoplePersonDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UIBarButtonItem *addItem; // @synthesize addItem=_addItem;
@property(retain, nonatomic) UIBarButtonItem *cancelItem; // @synthesize cancelItem=_cancelItem;
- (void).cxx_destruct;
- (void)peopleDataSource:(id)arg1 didApplyIncrementalChanges:(id)arg2;
- (void)peopleDataSourceMembersChanged:(id)arg1;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)_updateNavBarForIndexes:(id)arg1;
- (void)_addAction:(id)arg1;
- (void)_cancelAction:(id)arg1;
- (id)_rightBarItems;
- (id)_leftBarItems;
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)addSelectionToHomeScreen;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
- (long long)_personTypeForIndexPath:(id)arg1;
- (id)_changeMemberAtIndex:(id)arg1 toPersonType:(long long)arg2;
- (void)_calculateItemSize;
- (_Bool)_wantsCenteringLayout;
- (id)_flowLayout;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

