//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage;

@interface PXPeopleFaceTileImageRequestResult : NSObject
{
    _Bool _isDegraded;
    UIImage *_image;
    struct CGRect _faceRect;
}

@property(readonly, nonatomic) _Bool isDegraded; // @synthesize isDegraded=_isDegraded;
@property(readonly, nonatomic) struct CGRect faceRect; // @synthesize faceRect=_faceRect;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1 faceRect:(struct CGRect)arg2 isDegraded:(_Bool)arg3;

@end

