//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/PXPeopleDataSource.h>

#import <PhotosUICore/PHPhotoLibraryChangeObserver-Protocol.h>

@class NSString;

@interface PXPeoplePersonDataSource : PXPeopleDataSource <PHPhotoLibraryChangeObserver>
{
    long long _personType;
}

+ (id)hiddenPeopleDataSourceWithFetchLimit:(unsigned long long)arg1;
+ (id)otherPeopleDataSourceWithFetchLimit:(unsigned long long)arg1;
+ (id)importantPeopleDataSourceWithFetchLimit:(unsigned long long)arg1;
@property(nonatomic) long long personType; // @synthesize personType=_personType;
- (void)photoLibraryDidChange:(id)arg1;
- (CDUnknownBlockType)manualOrderComparator;
- (CDUnknownBlockType)defaultComparator;
- (void)_asyncLoadImageForItem:(id)arg1 targetSize:(struct CGSize)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (id)_membersForModelObjects:(id)arg1;
- (id)_applyChanges:(id)arg1;
- (void)_updateMember:(id)arg1 WithModelObject:(id)arg2;
- (id)_itemsArrayFromObjects:(id)arg1;
- (id)titleAtIndex:(unsigned long long)arg1;
- (void)stopListeningForChanges;
- (void)startListeningForChanges;
- (id)initWithName:(id)arg1 personType:(long long)arg2 fetchLimit:(unsigned long long)arg3;
- (id)initWithName:(id)arg1 personType:(long long)arg2 objects:(id)arg3;
- (id)initWithName:(id)arg1 objects:(id)arg2;
- (id)initWithName:(id)arg1 fetchResultBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

