//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <PhotosUICore/PXPeopleSuggestionManagerDelegate-Protocol.h>
#import <PhotosUICore/PXPeopleSummaryDelegate-Protocol.h>

@class NSString, PXAnimatedHeaderView, PXPeopleConfirmationSummaryViewController, PXPeopleSuggestionManager, PXPeopleSuggestionView, UILabel;

@interface PXPeopleBaseConfirmationViewController : UIViewController <PXPeopleSuggestionManagerDelegate, PXPeopleSummaryDelegate>
{
    PXPeopleSuggestionManager *_suggestionManager;
    PXPeopleSuggestionView *_suggestionView;
    PXAnimatedHeaderView *_headerView;
    UILabel *_descriptionLabel;
    PXPeopleConfirmationSummaryViewController *_summaryViewController;
}

@property(retain) PXPeopleConfirmationSummaryViewController *summaryViewController; // @synthesize summaryViewController=_summaryViewController;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) PXAnimatedHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) PXPeopleSuggestionView *suggestionView; // @synthesize suggestionView=_suggestionView;
@property(readonly) PXPeopleSuggestionManager *suggestionManager; // @synthesize suggestionManager=_suggestionManager;
- (void).cxx_destruct;
- (unsigned long long)autoConfirmedCountForSummaryViewController:(id)arg1;
- (unsigned long long)userConfirmedCountForSummaryViewController:(id)arg1;
- (id)faceCollectionForSummaryViewController:(id)arg1;
- (void)noMoreSuggestionsAvailableForSuggestionManager:(id)arg1;
- (void)suggestionManager:(id)arg1 hasNewSuggestionAvailable:(id)arg2;
- (void)confirmationCountUpdatedForSuggestionManager:(id)arg1;
- (void)doneTapped:(id)arg1;
- (void)performUndo:(id)arg1;
- (void)undoDeny:(id)arg1;
- (void)undoConfirm:(id)arg1;
- (void)denyTapped:(id)arg1;
- (void)confirmTapped:(id)arg1;
- (void)dismissSummary;
- (void)displaySummary;
- (void)presentSuggestion:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithPerson:(id)arg1 initialSuggestions:(id)arg2;
- (id)initWithFaceCollection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

