//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@interface UITabBarController (PhotosUICore)
- (struct CGRect)px_frameForTabItem:(unsigned long long)arg1 inCoordinateSpace:(id)arg2;
- (void)px_performAddToTabAnimation:(unsigned long long)arg1 withSnapshotView:(id)arg2;
- (_Bool)px_canPerformAddToTabAnimationForTab:(unsigned long long)arg1;
- (void)px_navigateToMemoryWithLocalIdentifier:(id)arg1;
@property(readonly, nonatomic, getter=px_isTabBarHidden) _Bool px_tabBarHidden;
@end

