//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUAlbumListViewControllerSpec.h>

@interface PUAlbumListViewControllerCommonPhoneSpec : PUAlbumListViewControllerSpec
{
}

- (_Bool)shouldUseCollageForCloudFeedPlaceholder;
- (_Bool)showsDeleteButtonOnCellContentView;
- (_Bool)canDisplaySearchActionInNavigationBar;
- (long long)albumDeletionConfirmationStyle;
- (id)feedViewControllerSpec;
- (id)photosPickerViewControllerSpec;
- (id)panoramaViewControllerSpec;
- (id)albumViewControllerSpec;
- (id)gridViewControllerSpec;
- (id)_nameOfRecentlyDeletedAlbumPlaceholderImage;
- (id)_nameOfHiddenAlbumPlaceholderImage;
- (id)_nameOfEmptySharedAlbumPlaceholderImage;
- (id)_nameOfAddSharedAlbumPlaceholderImage;
- (id)_nameOfEmptyAlbumPlaceholderImage;
- (double)sectionFooterHeight;
- (double)sectionHeaderHeight;
- (double)posterSubitemCornerRadius;
- (double)posterSquareCornerRadius;
- (struct UIOffset)stackOffset;
- (struct UIOffset)stackPerspectiveOffset;
- (struct UIEdgeInsets)stackPerspectiveInsets;
- (id)emptyStackPhotoDecoration;
- (id)stackPhotoDecoration;
- (unsigned long long)stackViewStyle;

@end

