//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUAlbumListViewControllerCommonPhoneSpec.h>

@interface PUAlbumListViewControllerCommonImagePickerSpec : PUAlbumListViewControllerCommonPhoneSpec
{
}

- (id)_nameOfRecentlyDeletedAlbumPlaceholderImage;
- (id)_nameOfHiddenAlbumPlaceholderImage;
- (id)_nameOfEmptySharedAlbumPlaceholderImage;
- (id)_nameOfAddSharedAlbumPlaceholderImage;
- (id)_nameOfEmptyAlbumPlaceholderImage;
- (_Bool)shouldUseCollageForCloudFeedPlaceholder;
- (_Bool)showsDeleteButtonOnCellContentView;
- (double)sectionFooterHeight;
- (double)sectionHeaderHeight;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;
- (long long)cellContentViewLayout;
- (void)configureStackViewWithGridStyle:(id)arg1;
- (struct CGSize)stackSize;
- (struct CGSize)imageSize;
- (_Bool)shouldUseTableView;

@end

