//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUAssetsDataSourceManager.h>

#import <PhotosUI/PUAssetsDataSourceManagerDelegate-Protocol.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface PUAssetExplorerReviewScreenAssetsDataSourceManager : PUAssetsDataSourceManager <PUAssetsDataSourceManagerDelegate>
{
    PUAssetsDataSourceManager *_originalDataSourceManager;
    NSDictionary *__replacementAssetsByUUID;
}

@property(copy, nonatomic, setter=_setReplacementAssetsByUUID:) NSDictionary *_replacementAssetsByUUID; // @synthesize _replacementAssetsByUUID=__replacementAssetsByUUID;
@property(readonly, nonatomic) PUAssetsDataSourceManager *originalDataSourceManager; // @synthesize originalDataSourceManager=_originalDataSourceManager;
- (void).cxx_destruct;
- (id)assetsDataSourceManagerInterestingAssetReferences:(id)arg1;
- (void)assetsDataSourceManager:(id)arg1 didChangeAssetsDataSource:(id)arg2;
- (void)_updateDataSource;
- (void)performChanges:(CDUnknownBlockType)arg1;
- (id)initWithOriginalDataSourceManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

