//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import <PhotosUI/PUAccessoryContentViewController-Protocol.h>
#import <PhotosUI/UITextFieldDelegate-Protocol.h>

@class NSMutableDictionary, NSString;
@protocol PUAccessoryContentViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface PUSampleAccessoryViewController : UITableViewController <UITextFieldDelegate, PUAccessoryContentViewController>
{
    id <PUAccessoryContentViewControllerDelegate> _accessoryContentViewControllerDelegate;
    NSMutableDictionary *__strings;
    struct UIEdgeInsets _contentInsets;
}

@property(retain, nonatomic) NSMutableDictionary *_strings; // @synthesize _strings=__strings;
@property(readonly, nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) __weak id <PUAccessoryContentViewControllerDelegate> accessoryContentViewControllerDelegate; // @synthesize accessoryContentViewControllerDelegate=_accessoryContentViewControllerDelegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGRect)contentBoundsInCoordinateSpace:(id)arg1;
- (_Bool)contentAreaContainsPoint:(struct CGPoint)arg1 inCoordinateSpace:(id)arg2;
- (void)setContentInsets:(struct UIEdgeInsets)arg1 changeReason:(long long)arg2;
- (struct CGSize)preferredContentSize;
- (long long)_numberOfRows;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct CGSize minimumContentSize;
@property(readonly) Class superclass;

@end

