//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/PXObservable.h>

#import <PhotosUI/PUMutableTimelineScrubberModel-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface PUTimelineScrubberModel : PXObservable <PUMutableTimelineScrubberModel>
{
    struct {
        _Bool scrubberRange;
        _Bool scrubberOffset;
        _Bool contentOffset;
    } _needsUpdateFlags;
    double _scrubbingRate;
    double _contentRange;
    double _contentOffset;
    double _scrubberRange;
    double _scrubberOffset;
    double __accelerationFactor;
    struct PUTimelineScrubberInsets _contentInsets;
    struct PUTimelineScrubberInsets _scrubberInsets;
}

@property(nonatomic, setter=_setAccelerationFactor:) double _accelerationFactor; // @synthesize _accelerationFactor=__accelerationFactor;
@property(readonly, nonatomic) struct PUTimelineScrubberInsets scrubberInsets; // @synthesize scrubberInsets=_scrubberInsets;
@property(readonly, nonatomic) struct PUTimelineScrubberInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(readonly, nonatomic) double scrubberOffset; // @synthesize scrubberOffset=_scrubberOffset;
@property(nonatomic, setter=_setScrubberRange:) double scrubberRange; // @synthesize scrubberRange=_scrubberRange;
@property(readonly, nonatomic) double contentOffset; // @synthesize contentOffset=_contentOffset;
@property(readonly, nonatomic) double contentRange; // @synthesize contentRange=_contentRange;
@property(readonly, nonatomic) double scrubbingRate; // @synthesize scrubbingRate=_scrubbingRate;
- (void)_invalidateContentOffset;
- (void)_invalidateScrubberOffset;
- (void)_invalidateScrubberRange;
- (_Bool)_needsUpdate;
- (void)_setNeedsUpdate;
- (void)_updateContentOffsetIfNeeded;
- (void)_updateScrubberOffsetIfNeeded;
- (void)_updateScrubberRangeIfNeeded;
- (void)_updateIfNeeded;
- (void)_setScrubberOffset:(double)arg1 fromSource:(unsigned long long)arg2;
- (void)_setContentOffset:(double)arg1 fromSource:(unsigned long long)arg2;
- (double)foreignOffsetForLocalOffset:(double)arg1 inLocalRange:(double)arg2 withLocalInsets:(struct PUTimelineScrubberInsets)arg3 foreignRange:(double)arg4 foreignInsets:(struct PUTimelineScrubberInsets)arg5 localToForeignRatio:(double)arg6;
- (double)contentOffsetForScrubberOffset:(double)arg1;
- (double)scrubberOffsetForContentOffset:(double)arg1;
- (void)setContentInsets:(struct PUTimelineScrubberInsets)arg1;
- (void)setScrubberOffset:(double)arg1;
- (void)setContentOffset:(double)arg1;
- (void)setContentRange:(double)arg1;
- (void)setScrubbingRate:(double)arg1;
- (void)didPerformChanges;
- (void)performChanges:(CDUnknownBlockType)arg1;
- (id)mutableChangeObject;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

