//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUI/PUWelcomeViewController.h>

@class NSLayoutConstraint, UIScrollView;

__attribute__((visibility("hidden")))
@interface PUWhatsNewWelcomeViewController : PUWelcomeViewController
{
    CDUnknownBlockType __completionHandler;
    UIScrollView *__scrollView;
    NSLayoutConstraint *__topConstraint;
}

+ (void)resetLastPresentationInfo;
+ (void)presentIfNecessaryFromViewController:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(readonly, copy, nonatomic) NSLayoutConstraint *_topConstraint; // @synthesize _topConstraint=__topConstraint;
@property(readonly, copy, nonatomic) UIScrollView *_scrollView; // @synthesize _scrollView=__scrollView;
@property(readonly, copy, nonatomic) CDUnknownBlockType _completionHandler; // @synthesize _completionHandler=__completionHandler;
- (void).cxx_destruct;
- (void)_handleContinueButton:(id)arg1;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)_initWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

