//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Home/HFItemBuilder.h>

#import <Home/HFWallpaperBuilder-Protocol.h>

@class HFWallpaper, NAFuture, NSString;

@interface HFHomeBuilder : HFItemBuilder <HFWallpaperBuilder>
{
    NSString *_name;
    NSString *_userNotes;
    HFWallpaper *_wallpaper;
    NAFuture *_loadedWallpaperFuture;
}

+ (Class)homeKitRepresentationClass;
@property(retain, nonatomic) NAFuture *loadedWallpaperFuture; // @synthesize loadedWallpaperFuture=_loadedWallpaperFuture;
@property(retain, nonatomic) HFWallpaper *wallpaper; // @synthesize wallpaper=_wallpaper;
@property(copy, nonatomic) NSString *userNotes; // @synthesize userNotes=_userNotes;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)updateUserNotes;
- (id)updateWallpaper;
- (id)updateName;
- (id)createHome;
- (id)performValidation;
- (id)commitItem;
- (id)wallpaperFuture;
- (void)setHome:(id)arg1;
- (id)initWithExistingObject:(id)arg1 inHome:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

