//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Home/HFHomeManagerObserver-Protocol.h>
#import <Home/HFHomeObserver-Protocol.h>

@class HFWallpaperCloudManager, HFWallpaperFileManager, NSArray, NSOperationQueue, NSString;
@protocol HFNamedWallpaperSource, HFProcessedWallpaperSource;

@interface HFWallpaperManager : NSObject <HFHomeManagerObserver, HFHomeObserver>
{
    id <HFNamedWallpaperSource> _namedWallpaperSource;
    id <HFProcessedWallpaperSource> _processedWallpaperSource;
    HFWallpaperFileManager *_fileManager;
    HFWallpaperCloudManager *_cloudManager;
    NSOperationQueue *_operationQueue;
    NSArray *_cachedWallpapers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *cachedWallpapers; // @synthesize cachedWallpapers=_cachedWallpapers;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) HFWallpaperCloudManager *cloudManager; // @synthesize cloudManager=_cloudManager;
@property(retain, nonatomic) HFWallpaperFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(retain, nonatomic) id <HFProcessedWallpaperSource> processedWallpaperSource; // @synthesize processedWallpaperSource=_processedWallpaperSource;
@property(retain, nonatomic) id <HFNamedWallpaperSource> namedWallpaperSource; // @synthesize namedWallpaperSource=_namedWallpaperSource;
- (void).cxx_destruct;
- (long long)collectionTypeForHomeKitObject:(id)arg1;
- (void)dispatchWallpaperChangedForHomeKitObject:(id)arg1;
- (id)_storeOriginalWallpaper:(id)arg1 homeKitObject:(id)arg2 updateCloud:(_Bool)arg3;
- (id)_storeCacheWallpaper:(id)arg1 homeKitObject:(id)arg2;
- (id)_loadCloudWallpaperVariant:(long long)arg1 homeKitObject:(id)arg2;
- (id)_loadDiskWallpaperVariant:(long long)arg1 homeKitObject:(id)arg2;
- (id)_loadCachedWallpaperVariant:(long long)arg1 homeKitObject:(id)arg2;
- (id)_loadWallpaperVariant:(long long)arg1 homeKitObject:(id)arg2;
- (void)loadWallpaperVariants:(id)arg1 homeKitObject:(id)arg2;
- (void)preloadWallpapersForHome:(id)arg1;
- (void)home:(id)arg1 didUpdateApplicationDataForRoom:(id)arg2;
- (void)homeDidUpdateApplicationData:(id)arg1;
- (void)homeKitDispatcher:(id)arg1 manager:(id)arg2 didChangeHome:(id)arg3;
- (void)homeManagerDidFinishInitialDatabaseLoad:(id)arg1;
- (id)setCurrentWallpaper:(id)arg1 homeKitObject:(id)arg2;
- (id)currentWallpaperForVariant:(long long)arg1 homeKitObject:(id)arg2;
- (void)registerProcessedWallpaperSource:(id)arg1;
- (id)namedWallpaperForIdentifier:(id)arg1;
- (id)defaultNamedWallpaperForCollection:(long long)arg1;
- (id)allNamedWallpaperIdentifiersForCollection:(long long)arg1;
- (void)registerNamedWallpaperSource:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

