//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeKit/HMHome.h>

@interface HMHome (Additions)
- (id)hf_updateColorPalette:(id)arg1;
- (id)hf_colorPalette;
- (id)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:(_Bool)arg1;
- (_Bool)hf_homeHasOnboarded;
- (id)hf_setNotesApplicationData:(id)arg1;
- (id)hf_notesApplicationData;
- (id)hf_reorderableActionSetsList;
- (id)hf_reorderableServicesList;
- (id)hf_allCharacteristics;
- (id)hf_characteristicWithIdentifier:(id)arg1 ofServiceWithIdentifier:(id)arg2;
- (id)hf_allServices;
- (id)hf_servicesWithIdentifiers:(id)arg1;
- (id)hf_serviceWithIdentifier:(id)arg1;
- (id)hf_serviceGroupsForService:(id)arg1;
- (id)hf_serviceGroupWithIdentifier:(id)arg1;
- (id)hf_allBridgeAccessories;
- (id)hf_accessoryWithIdentifier:(id)arg1;
- (id)hf_actionSetsAffectingCharacteristic:(id)arg1;
- (id)hf_actionSetWithIdentifier:(id)arg1;
- (id)hf_allNonEmptyActionSets;
- (id)hf_triggersByIdentifier;
- (id)hf_triggersAffectingActionSet:(id)arg1;
- (id)hf_triggerWithIdentifier:(id)arg1;
- (id)hf_roomWithIdentifier:(id)arg1;
- (id)hf_zoneForRoom:(id)arg1;
- (id)hf_createDestinationsArray;
- (_Bool)hf_currentUserIsAdministrator;
- (id)hf_characteristicValueManager;
- (id)hf_otherAccessories;
- (id)hf_unassignedRooms;
- (id)hf_allRooms;
@end

