//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeKit/HMRoom.h>

@class HMHome;

@interface HMRoom (HFAdditions)
- (id)hf_allServices;

// Remaining properties
@property(readonly, nonatomic) __weak HMHome *home; // @dynamic home;
@end

