//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate;

@interface FFFriendListSection : NSObject
{
    NSDate *_startDate;
    NSArray *_rows;
}

@property(retain, nonatomic) NSArray *rows; // @synthesize rows=_rows;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
- (void).cxx_destruct;
- (_Bool)containsFriendListRow:(id)arg1;
- (id)initWithDate:(id)arg1 andRows:(id)arg2;

@end

