//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreCDPInternal/CDPDRecoveryFlowController.h>

#import <CoreCDPInternal/CDPDRemoteDeviceSecretValidatorDelegate-Protocol.h>

@class NSString;

@interface CDPDRecoveryValidatedJoinFlowController : CDPDRecoveryFlowController <CDPDRemoteDeviceSecretValidatorDelegate>
{
}

- (_Bool)secretValidator:(id)arg1 shouldAcceptRecoveryError:(id *)arg2;
- (void)secretValidatorWillAttemptRecovery;
- (void)cancelRemoteSecretValidatorApplicationToJoinCircle:(id)arg1;
- (void)remoteSecretValidator:(id)arg1 applyToJoinCircleWithJoinHandler:(CDUnknownBlockType)arg2;
- (unsigned long long)_escapeOfferForDevices:(id)arg1 remoteApproval:(_Bool)arg2 stringrayStatus:(_Bool)arg3;
- (id)recoveryValidatorWithDevices:(id)arg1 forMultipleICSC:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

