//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Navigation/NSSecureCoding-Protocol.h>

@class NSString;

@interface MNSettings : NSObject <NSSecureCoding>
{
    unsigned long long _voiceVolume;
    unsigned long long _distanceUnits;
    _Bool _pauseSpokenAudio;
    _Bool _drivingVoiceGuidance;
    _Bool _walkingVoiceGuidance;
    _Bool _beepBeforeInstruction;
    NSString *_voiceLanguage;
    double _etaRequestInterval;
    double _initialRequestDelay;
    double _backgroundTimeWindow;
    long long _fakeTrafficIncidentAlert;
    long long _acceptFasterReroute;
    double _alightSignalTimeBuffer;
    _Bool _useTraceDirectionsResponses;
    _Bool _useTraceETAResponses;
    _Bool _isTracePlaybackCameraTestMode;
}

+ (_Bool)supportsSecureCoding;
+ (id)_mapsSettings;
@property(readonly, nonatomic) _Bool isTracePlaybackCameraTestMode; // @synthesize isTracePlaybackCameraTestMode=_isTracePlaybackCameraTestMode;
@property(readonly, nonatomic) _Bool useTraceETAResponses; // @synthesize useTraceETAResponses=_useTraceETAResponses;
@property(readonly, nonatomic) _Bool useTraceDirectionsResponses; // @synthesize useTraceDirectionsResponses=_useTraceDirectionsResponses;
@property(readonly, nonatomic) double alightSignalTimeBuffer; // @synthesize alightSignalTimeBuffer=_alightSignalTimeBuffer;
@property(readonly, nonatomic) long long acceptFasterReroute; // @synthesize acceptFasterReroute=_acceptFasterReroute;
@property(readonly, nonatomic) long long fakeTrafficIncidentAlert; // @synthesize fakeTrafficIncidentAlert=_fakeTrafficIncidentAlert;
@property(readonly, nonatomic) double backgroundTimeWindow; // @synthesize backgroundTimeWindow=_backgroundTimeWindow;
@property(readonly, nonatomic) double initialRequestDelay; // @synthesize initialRequestDelay=_initialRequestDelay;
@property(readonly, nonatomic) double etaRequestInterval; // @synthesize etaRequestInterval=_etaRequestInterval;
@property(readonly, nonatomic) NSString *voiceLanguage; // @synthesize voiceLanguage=_voiceLanguage;
@property(readonly, nonatomic) _Bool beepBeforeInstruction; // @synthesize beepBeforeInstruction=_beepBeforeInstruction;
@property(readonly, nonatomic) _Bool walkingVoiceGuidance; // @synthesize walkingVoiceGuidance=_walkingVoiceGuidance;
@property(readonly, nonatomic) _Bool drivingVoiceGuidance; // @synthesize drivingVoiceGuidance=_drivingVoiceGuidance;
@property(readonly, nonatomic) _Bool pauseSpokenAudio; // @synthesize pauseSpokenAudio=_pauseSpokenAudio;
@property(readonly, nonatomic) unsigned long long distanceUnits; // @synthesize distanceUnits=_distanceUnits;
@property(readonly, nonatomic) unsigned long long voiceVolume; // @synthesize voiceVolume=_voiceVolume;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

