//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, PGPlaybackProgress, PGTimer, _PGPlaybackProgressIndicatorMaskView;

@interface PGPlaybackProgressIndicator : UIView
{
    PGPlaybackProgress *_playbackProgress;
    NSArray *_loadedTimeRanges;
    PGTimer *_playbackProgressTimer;
    double _currentProgress;
    UIView *_containerView;
    _PGPlaybackProgressIndicatorMaskView *_loadedTimeRangesMaskView;
    _PGPlaybackProgressIndicatorMaskView *_playbackProgressMaskView;
}

- (void).cxx_destruct;
- (void)_updateLoadedTimeRangesMaskViewMaskRanges;
- (void)_updatePlaybackProgressMaskViewMaskRanges;
- (void)_updatePlaybackProgressTimer;
- (struct CGSize)intrinsicContentSize;
- (void)setBounds:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *loadedTimeRanges;
@property(retain, nonatomic) PGPlaybackProgress *playbackProgress;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

