//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpotlightUI/NSObject-Protocol.h>

@class NSArray, NSError, NSString, SPDaemonQueryToken, SPResultSet;

@protocol SPDaemonQueryDelegate <NSObject>
- (void)searchDaemonSuggestionsArray:(NSArray *)arg1;
- (void)searchDaemonRankingLog:(NSString *)arg1;
- (void)searchDaemonQueryCompleted:(SPDaemonQueryToken *)arg1;
- (void)searchDaemonQueryReset:(SPDaemonQueryToken *)arg1;
- (void)searchDaemonQuery:(SPDaemonQueryToken *)arg1 encounteredError:(NSError *)arg2;
- (void)searchDaemonQuery:(SPDaemonQueryToken *)arg1 addedResults:(struct NSObject *)arg2;
- (void)searchDaemonQuery:(SPDaemonQueryToken *)arg1 addedResultSections:(NSArray *)arg2;

@optional
- (void)searchDaemonQuery:(SPDaemonQueryToken *)arg1 gotResultSet:(SPResultSet *)arg2 replace:(_Bool)arg3 complete:(_Bool)arg4 finished:(_Bool)arg5;
@end

