//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

@class NSArray, SPSearchResult, SPSearchResultSection;

@interface SPUISearchMoviesViewController : UICollectionViewController
{
    SPSearchResult *_result;
    SPSearchResultSection *_section;
    NSArray *_movies;
}

@property(retain) NSArray *movies; // @synthesize movies=_movies;
@property(retain) SPSearchResultSection *section; // @synthesize section=_section;
@property(retain) SPSearchResult *result; // @synthesize result=_result;
- (void).cxx_destruct;

@end

