//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PassKitCore/PKPaymentOverlayableRequest.h>

@class NSData, NSString, PKPaymentEligibilityResponse;

@interface PKPaymentProvisioningRequest : PKPaymentOverlayableRequest
{
    PKPaymentEligibilityResponse *_eligibilityResponse;
    NSString *_cardholderName;
    NSString *_cardSecurityCode;
    NSData *_activationData;
    NSData *_deviceScore;
}

@property(copy, nonatomic) NSData *deviceScore; // @synthesize deviceScore=_deviceScore;
@property(copy, nonatomic) NSData *activationData; // @synthesize activationData=_activationData;
@property(copy, nonatomic) NSString *cardSecurityCode; // @synthesize cardSecurityCode=_cardSecurityCode;
@property(copy, nonatomic) NSString *cardholderName; // @synthesize cardholderName=_cardholderName;
@property(retain, nonatomic) PKPaymentEligibilityResponse *eligibilityResponse; // @synthesize eligibilityResponse=_eligibilityResponse;
- (void).cxx_destruct;
- (void)_urlRequestWithServiceURL:(id)arg1 deviceIdentifier:(id)arg2 account:(id)arg3 certChain:(id)arg4 devSigned:(_Bool)arg5 deviceData:(id)arg6 webService:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (id)initWithEligibilityResponse:(id)arg1;

@end

