//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSSecureCoding-Protocol.h>

@class NSArray, NSDate, NSDictionary, NSString, PKVerificationChannel;

@interface PKVerificationRequestRecord : NSObject <NSSecureCoding>
{
    long long _verificationStatus;
    NSString *_passUniqueID;
    NSDate *_date;
    PKVerificationChannel *_channel;
    NSArray *_allChannels;
    NSDictionary *_requiredFieldData;
}

+ (_Bool)supportsSecureCoding;
+ (id)verificationRequestRecordForPass:(id)arg1;
@property(copy, nonatomic) NSDictionary *requiredFieldData; // @synthesize requiredFieldData=_requiredFieldData;
@property(copy, nonatomic) NSArray *allChannels; // @synthesize allChannels=_allChannels;
@property(copy, nonatomic) PKVerificationChannel *channel; // @synthesize channel=_channel;
@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *passUniqueID; // @synthesize passUniqueID=_passUniqueID;
@property(nonatomic) long long verificationStatus; // @synthesize verificationStatus=_verificationStatus;
- (void).cxx_destruct;
- (id)requiredVerificationFields;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

