//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/NSObject-Protocol.h>

@class FCAssetHandle;
@protocol FCOperationCanceling><FCOperationPrioritizing;

@protocol FCAssetHandleDelegate <NSObject>
- (id <FCOperationCanceling><FCOperationPrioritizing>)fetchFileForAssetHandle:(FCAssetHandle *)arg1 completion:(void (^)(NSString *, _Bool, NSError *))arg2;
@end

