//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface FCCKOrderFeedResponse : NSObject
{
    _Bool _reachedEnd;
    _Bool _reachedMinOrder;
    _Bool _wasDropped;
    _Bool _reachedOrderLimit;
    NSString *_feedID;
    NSArray *_feedItemAndArticleRecords;
}

@property(nonatomic) _Bool reachedOrderLimit; // @synthesize reachedOrderLimit=_reachedOrderLimit;
@property(nonatomic) _Bool wasDropped; // @synthesize wasDropped=_wasDropped;
@property(readonly, nonatomic) _Bool reachedMinOrder; // @synthesize reachedMinOrder=_reachedMinOrder;
@property(nonatomic) _Bool reachedEnd; // @synthesize reachedEnd=_reachedEnd;
@property(copy, nonatomic) NSArray *feedItemAndArticleRecords; // @synthesize feedItemAndArticleRecords=_feedItemAndArticleRecords;
@property(copy, nonatomic) NSString *feedID; // @synthesize feedID=_feedID;
- (void).cxx_destruct;
- (id)description;

@end

