//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCCKOperation.h>

@class CKRecordZoneID, CKServerChangeToken, FCCKDatabase, NSArray, NSError, NSMutableDictionary, NSMutableSet;

@interface FCCKFetchRecordChangesOperation : FCCKOperation
{
    _Bool _fetchAllChanges;
    _Bool _moreChangesToFetch;
    FCCKDatabase *_database;
    CKRecordZoneID *_recordZoneID;
    CKServerChangeToken *_serverChangeToken;
    NSArray *_desiredKeys;
    CDUnknownBlockType _finishedBlock;
    NSMutableDictionary *_allChangedRecordsByID;
    NSMutableSet *_allDeletedRecordIDs;
    NSError *_error;
}

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) _Bool moreChangesToFetch; // @synthesize moreChangesToFetch=_moreChangesToFetch;
@property(retain, nonatomic) NSMutableSet *allDeletedRecordIDs; // @synthesize allDeletedRecordIDs=_allDeletedRecordIDs;
@property(retain, nonatomic) NSMutableDictionary *allChangedRecordsByID; // @synthesize allChangedRecordsByID=_allChangedRecordsByID;
@property(copy, nonatomic) CDUnknownBlockType finishedBlock; // @synthesize finishedBlock=_finishedBlock;
@property(nonatomic) _Bool fetchAllChanges; // @synthesize fetchAllChanges=_fetchAllChanges;
@property(copy, nonatomic) NSArray *desiredKeys; // @synthesize desiredKeys=_desiredKeys;
@property(retain, nonatomic) CKServerChangeToken *serverChangeToken; // @synthesize serverChangeToken=_serverChangeToken;
@property(retain, nonatomic) CKRecordZoneID *recordZoneID; // @synthesize recordZoneID=_recordZoneID;
@property(retain, nonatomic) FCCKDatabase *database; // @synthesize database=_database;
- (void).cxx_destruct;
- (void)_continueFetchingRecords;
- (void)operationWillFinishWithError:(id)arg1;
- (void)resetForRetry;
- (void)performOperation;
- (_Bool)validateOperation;
- (id)init;

@end

