//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCOperation.h>

@class FCCloudContext, FCFeedViewport, FCFeedViewportBookmark, FCFeedViewportDiff;

@interface FCFeedViewportUpdateHeadlinesOperation : FCOperation
{
    FCCloudContext *_context;
    FCFeedViewport *_viewport;
    double _maxArticleAge;
    FCFeedViewportBookmark *_fromBookmark;
    FCFeedViewportBookmark *_toBookmark;
    CDUnknownBlockType _updateHeadlinesCompletionHandler;
    FCFeedViewport *_resultViewport;
    FCFeedViewportDiff *_resultDiff;
}

@property(retain, nonatomic) FCFeedViewportDiff *resultDiff; // @synthesize resultDiff=_resultDiff;
@property(retain, nonatomic) FCFeedViewport *resultViewport; // @synthesize resultViewport=_resultViewport;
@property(copy, nonatomic) CDUnknownBlockType updateHeadlinesCompletionHandler; // @synthesize updateHeadlinesCompletionHandler=_updateHeadlinesCompletionHandler;
@property(copy, nonatomic) FCFeedViewportBookmark *toBookmark; // @synthesize toBookmark=_toBookmark;
@property(copy, nonatomic) FCFeedViewportBookmark *fromBookmark; // @synthesize fromBookmark=_fromBookmark;
@property(nonatomic) double maxArticleAge; // @synthesize maxArticleAge=_maxArticleAge;
@property(retain, nonatomic) FCFeedViewport *viewport; // @synthesize viewport=_viewport;
@property(retain, nonatomic) FCCloudContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)operationWillFinishWithError:(id)arg1;
- (void)performOperation;
- (_Bool)validateOperation;

@end

