//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol FCContentContext;

@interface FCFlintResourceManager : NSObject
{
    id <FCContentContext> _context;
}

@property(readonly, nonatomic) id <FCContentContext> context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)cachedResourcesWithIdentifiers:(id)arg1;
- (id)fetchResourcesWithIdentifiers:(id)arg1 downloadAssets:(_Bool)arg2 networkPriority:(long long)arg3 callBackQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)initWithContext:(id)arg1;
- (id)init;

@end

