//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCModifyRecordsCommand.h>

@interface FCModifySubscriptionsCommand : FCModifyRecordsCommand
{
}

+ (id)desiredKeys;
- (_Bool)mergeLocalRecord:(id)arg1 withRemoteRecord:(id)arg2;
- (id)recordZoneName;
- (id)initWithSubscriptions:(id)arg1 merge:(_Bool)arg2;

@end

