//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCFeedGroupEmittingOperation.h>

@interface FCMoreForYouGroupEmittingOperation : FCFeedGroupEmittingOperation
{
}

- (id)_joinedFeedTransformation;
- (id)_editorialFeedTransformation;
- (id)_nonEditorialFeedTransformationWithFeedContext:(id)arg1;
- (void)performOperation;

@end

