//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface FCSolMove : NSObject
{
    NSMutableSet *_articles;
    NSMutableSet *_orphans;
    unsigned long long _score;
}

+ (void)rankMoves:(id)arg1 ungroupedArticles:(id)arg2 remainingTags:(id)arg3 articlesByTag:(id)arg4 heuristic:(id)arg5 comparator:(CDUnknownBlockType)arg6;
+ (CDUnknownBlockType)filteredMoveComparator:(long long)arg1;
+ (CDUnknownBlockType)moveComparator:(long long)arg1;
@property(nonatomic) unsigned long long score; // @synthesize score=_score;
@property(retain, nonatomic) NSMutableSet *orphans; // @synthesize orphans=_orphans;
@property(retain, nonatomic) NSMutableSet *articles; // @synthesize articles=_articles;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long numOrphans;
@property(readonly, nonatomic) unsigned long long numArticles;
- (id)initWithArticles:(id)arg1 orphans:(id)arg2;

@end

