//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCRecordSource.h>

@interface FCTagRecordSource : FCRecordSource
{
}

+ (double)defaultFetchOperationMaximumCachedAge;
+ (unsigned long long)defaultFetchOperationCachePolicy;
+ (id)recordFromCKRecord:(id)arg1 base:(id)arg2;
+ (unsigned long long)dataSizeLimit;
+ (unsigned long long)storeVersion;
+ (id)storeFilename;
+ (id)localizedKeysByOriginalKey;
+ (id)localizableKeys;
+ (id)genericKeys;
+ (id)desiredKeys;
+ (id)recordType;
- (id)saveTagRecords:(id)arg1;

@end

