//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsTransport/NTPBFeedItem.h>

#import <NewsCore/FCFeedPersonalizingArticle-Protocol.h>

@class NSArray, NSDate, NSString;

@interface NTPBFeedItem (FeedPersonalization) <FCFeedPersonalizingArticle>
- (_Bool)mustShow;
@property(readonly, nonatomic) unsigned long long articleContentType;
@property(readonly, nonatomic) _Bool hasGlobalUserFeedback;
@property(readonly, nonatomic) double globalUserFeedback;
@property(readonly, copy, nonatomic) NSString *publisherID;
@property(readonly, nonatomic) unsigned long long halfLife;
@property(readonly, copy, nonatomic) NSDate *publishDate;
@property(readonly, copy, nonatomic) NSString *sourceFeedID;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *articleID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isPaid;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSArray *topicIDs;
@end

