//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Photos/PHAssetPropertySet.h>

@class NSString;

@interface PHAssetOriginalMetadataProperties : PHAssetPropertySet
{
    _Bool _isOriginalSRGB;
    short _originalHeight;
    short _originalWidth;
    short _originalExifOrientation;
    int _originalFilesize;
    NSString *_originalAssetsUUID;
    NSString *_originalFilename;
    NSString *_originalPath;
}

+ (id)propertiesToFetch;
+ (id)propertySetName;
@property(readonly, nonatomic) _Bool isOriginalSRGB; // @synthesize isOriginalSRGB=_isOriginalSRGB;
@property(readonly, nonatomic) NSString *originalPath; // @synthesize originalPath=_originalPath;
@property(readonly, nonatomic) int originalFilesize; // @synthesize originalFilesize=_originalFilesize;
@property(readonly, nonatomic) short originalExifOrientation; // @synthesize originalExifOrientation=_originalExifOrientation;
@property(readonly, nonatomic) NSString *originalFilename; // @synthesize originalFilename=_originalFilename;
@property(readonly, nonatomic) short originalWidth; // @synthesize originalWidth=_originalWidth;
@property(readonly, nonatomic) short originalHeight; // @synthesize originalHeight=_originalHeight;
@property(readonly, nonatomic) NSString *originalAssetsUUID; // @synthesize originalAssetsUUID=_originalAssetsUUID;
- (void).cxx_destruct;
- (id)initWithFetchDictionary:(id)arg1 asset:(id)arg2 prefetched:(_Bool)arg3;

@end

