//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Typedef'd Structures

// Ambiguous groups
typedef struct {
    unsigned int paidSubscriptionConversionPointType:1;
    unsigned int parentFeedType:1;
    unsigned int resultType:1;
    unsigned int userAction:1;
    unsigned int arrivedFromAd:1;
    unsigned int subscriptionOnlyArticlePreview:1;
} CDStruct_945473b1;

typedef struct {
    unsigned int coverArticleWidgetArticleCount:1;
} CDStruct_bb0d9f0d;

typedef struct {
    unsigned int viewType:1;
} CDStruct_372a990c;

