//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <NewsTransport/NSCopying-Protocol.h>

@class NSMutableArray, NSString, NTPBDate, NTPBFeedViewportEdition;

@interface NTPBFeedViewportGap : PBCodable <NSCopying>
{
    struct {
        int *list;
        unsigned long long count;
        unsigned long long size;
    } _groupEmitterIDRefs;
    NSMutableArray *_cursors;
    NSString *_identifier;
    NTPBFeedViewportEdition *_lastCompletedEdition;
    NTPBDate *_modificationDate;
    NTPBDate *_refreshDate;
    _Bool _reachedEnd;
    struct {
        unsigned int reachedEnd:1;
    } _has;
}

+ (Class)cursorsType;
@property(retain, nonatomic) NTPBFeedViewportEdition *lastCompletedEdition; // @synthesize lastCompletedEdition=_lastCompletedEdition;
@property(retain, nonatomic) NSMutableArray *cursors; // @synthesize cursors=_cursors;
@property(nonatomic) _Bool reachedEnd; // @synthesize reachedEnd=_reachedEnd;
@property(retain, nonatomic) NTPBDate *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(retain, nonatomic) NTPBDate *refreshDate; // @synthesize refreshDate=_refreshDate;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasLastCompletedEdition;
- (id)cursorsAtIndex:(unsigned long long)arg1;
- (unsigned long long)cursorsCount;
- (void)addCursors:(id)arg1;
- (void)clearCursors;
- (void)setGroupEmitterIDRefs:(int *)arg1 count:(unsigned long long)arg2;
- (int)groupEmitterIDRefAtIndex:(unsigned long long)arg1;
- (void)addGroupEmitterIDRef:(int)arg1;
- (void)clearGroupEmitterIDRefs;
@property(readonly, nonatomic) int *groupEmitterIDRefs;
@property(readonly, nonatomic) unsigned long long groupEmitterIDRefsCount;
@property(nonatomic) _Bool hasReachedEnd;
@property(readonly, nonatomic) _Bool hasModificationDate;
@property(readonly, nonatomic) _Bool hasRefreshDate;
@property(readonly, nonatomic) _Bool hasIdentifier;
- (void)dealloc;

@end

