//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSURL;

@interface CKAssistantPerson : NSObject
{
    NSURL *_contactID;
    NSString *_label;
}

@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(retain, nonatomic) NSURL *contactID; // @synthesize contactID=_contactID;
- (void).cxx_destruct;

@end

