//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UILabel;

@interface CKBadgeView : UIView
{
    unsigned long long _value;
    UILabel *_countLabel;
    NSLayoutConstraint *_heightConstraint;
    NSLayoutConstraint *_zeroWidthConstraint;
    NSLayoutConstraint *_roundWidthConstraint;
    NSLayoutConstraint *_pillWidthConstraint;
}

@property(readonly, nonatomic) NSLayoutConstraint *pillWidthConstraint; // @synthesize pillWidthConstraint=_pillWidthConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *roundWidthConstraint; // @synthesize roundWidthConstraint=_roundWidthConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *zeroWidthConstraint; // @synthesize zeroWidthConstraint=_zeroWidthConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(readonly, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(nonatomic) unsigned long long value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

