//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <ChatKit/UIScrollViewDelegate-Protocol.h>

@class NSString, UIScrollView;
@protocol CKBrowserSwitcherScrollPreventerDelegate;

@interface CKBrowserSwitcherScrollPreventer : UIView <UIScrollViewDelegate>
{
    _Bool _engaged;
    _Bool _scrollEnabled;
    _Bool _lastOffsetChangeFromHost;
    id <CKBrowserSwitcherScrollPreventerDelegate> _delegate;
    UIScrollView *_horizontalScrollView;
    UIScrollView *_verticalScrollView;
    struct CGPoint _previousScrollPoint;
}

@property(nonatomic) _Bool lastOffsetChangeFromHost; // @synthesize lastOffsetChangeFromHost=_lastOffsetChangeFromHost;
@property(nonatomic) struct CGPoint previousScrollPoint; // @synthesize previousScrollPoint=_previousScrollPoint;
@property(retain, nonatomic) UIScrollView *verticalScrollView; // @synthesize verticalScrollView=_verticalScrollView;
@property(retain, nonatomic) UIScrollView *horizontalScrollView; // @synthesize horizontalScrollView=_horizontalScrollView;
@property(nonatomic) __weak id <CKBrowserSwitcherScrollPreventerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
@property(nonatomic, getter=isEngaged) _Bool engaged; // @synthesize engaged=_engaged;
- (void).cxx_destruct;
@property(nonatomic) struct CGSize contentSize;
@property(nonatomic) struct CGPoint contentOffset;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

