//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2016 09:41:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ChatKit/NSObject-Protocol.h>

@class CKSharedContentsCollectionViewCell;

@protocol CKSharedContentsCollectionViewCellDelegate <NSObject>
- (void)performAction:(SEL)arg1 forSharedContentsCollectionViewCell:(CKSharedContentsCollectionViewCell *)arg2;
- (void)sharedContentsCollectionViewCellDidTap:(CKSharedContentsCollectionViewCell *)arg1;
@end

